fluent/fluent-package-builder

.gitignore, Gemfile, Gemfile.lock, Rakefile
まずはgem installで特定のディレクトリにインストールするRakefileを作成しました。
全部Rakefileに寄せてしまえば、Apache Arrowのパッケージングシステムに後々統合できそうな気がします！
=> Add Rakefile for core_gems, fluentd, and plugin_gems installation tasks

Rakefile, resources/etc/td-agent/logrotate.d/td-agent.logrotate, resources/etc/td-agent/td-agent.conf, resources/etc/td-agent/td-agent.conf.tmpl, td-agent-package-task.rb, templates/etc/td-agent/logrotate.d/td-agent.logrotate, templates/etc/td-agent/td-agent.conf, templates/etc/td-agent/td-agent.conf.tmpl, templates/usr/sbin/td-agent-gem.erb, templates/usr/sbin/td-agent.erb, yum/td-agent.spec.in
Currently, the following files are installed into RPM:
* /etc/td-agent
* /usr/sbin
=> Introduce generating configuration files from templates feature

Rakefile, templates/etc/systemd/td-agent.service.erb, templates/usr/sbin/td-agent.erb, yum/td-agent.spec.in
* Generate Systemd Unit file
* Install Systemd Unit files into RPM
* Correct directories' permissions
=> Generate and install Systemd Unit file

Rakefile, debian/rules, debian/td-agent.install, templates/package-scripts/td-agent/deb/postinst, templates/package-scripts/td-agent/deb/postrm, templates/package-scripts/td-agent/deb/prerm
* Generate package scripts for deb package
* Install systemd unit file and etc/td-agent/* files into deb package
TODO: gracefully td-agent service stop in deb package scripts
=> Install unitfile and package scripts deb

td-agent/config.rb, td-agent/core_gems.rb, td-agent/debian/changelog, td-agent/plugin_gems.rb
=> Upgrade fluentd and gems to be equivalent to td agent3.7.0

td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/debian/control
* libedit2
* libtinfo
* libyaml
I've added more dependent libraries for apt platforms.
=> apt: Add more dependent libraries

td-agent/Rakefile
* gem's cache files and test files
* *.o
See also: https://github.com/treasure-data/omnibus-td-agent/blob/05a1f1a43732383828f4cbec47e393773c14acea/config/software/td-agent-cleanup.rb
=> Remove needless files in packages

Vagrantfile
手元ではVagrantで動作確認をしていたので、手軽に動作確認ができるといいなと思いました。
=> Add Vagrantfile for td-agent packages confirmation

lib/yum/build.sh, td-agent/yum/amazonlinux-2-aarch64/from, td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/amazonlinux-2/qemu-dummy-static, td-agent/yum/td-agent.spec.in
=> Support Amazon Linux 2

td-agent/Rakefile
It will fix E: zero-length lintian error.
=> Remove needless files

td-agent/Rakefile
It fixes W: hidden-file-or-dir
=> rpm: remove needless hidden file

td-agent/yum/td-agent.spec.in
%preun section and upgrade sequence wasn't migrated from omnibus-td-agent.
=> rpm: fix missing %preun and upgrade regression

td-agent/yum/td-agent.spec.in
/var/log/td-agent/buffer
ref. https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L54
/etc/td-agent/plugin
ref. https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/rpm/post#L24
=> rpm: add missing owned directory

README.md
=> README.md: Fix the wrong instruction for AArch64 targets

td-agent/Rakefile, td-agent/debian/td-agent.install
=> deb: Add tmpfiles.d configuration

td-agent/yum/td-agent.spec.in
Add service when install td-agent first time.
=> rpm: fix E: fix-postin-without-chkconfig

.github/workflows/apt.yml, .github/workflows/yum.yml
Using if condition branches is a bit messy work flow.
Splitting linux workflow into apt and yum should be simple.
=> Split workflows

.travis.yml
We should also build Amazon Linux 2 and Ubuntu Focal arm64 packages.
=> Build additional arm64 packages

README.md
It is helpful not to shoot yourself in the foot.
=> Update prerequisites for Windows package

.github/workflows/apt.yml, Vagrantfile, td-agent/Rakefile, td-agent/apt/ubuntu-xenial/Dockerfile, td-agent/apt/ubuntu-xenial/qemu-dummy-static
Ubuntu doesn't support xenial-backports for Arm64 environment, so add only amd64.
=> Add Ubuntu xenial

.github/workflows/windows.yml, td-agent/msi/install-test.ps1
=> Add installation test for Windows Installer

README.md, td-agent/Rakefile
Fixes #160.
I've added short circuit rake task for updating lockfile.
=> Add lockfile update rake task

td-agent/yum/install-test.sh
=> rpm: execute install/remove/upgrade test

README.md
FIxes https://github.com/fluent-plugins-nursery/td-agent-builder/issues/133.
=> Add MSYS2 note for Windows package

.github/workflows/apt.yml, .github/workflows/yum.yml, Rakefile, td-agent-apt-source/Rakefile
And also fixes upload package name glitches which cause invalid package name.
=> Build apt source deb packages

td-agent/Rakefile
=> Bundle Gemfile and Gemfile.lock

td-agent/msi/Dockerfile
=> msi: Upgrade using MSYS2 version to 20200816.0.0

README.md
=> Add missing bundler and apt source package explanation

td-agent/Rakefile
=> Use logger to get rid of puts

.github/workflows/apt.yml, .github/workflows/yum.yml, td-agent/apt/commonvar.sh, td-agent/apt/install-test.sh, td-agent/apt/piuparts-test.sh, td-agent/apt/serverspec-test.sh, td-agent/msi/install-test.ps1, td-agent/yum/install-test.sh, td-agent/yum/serverspec-test.sh
It is easy to recognize which steps are failed.
Closes: #199
=> CI: split github test cases

.travis.yml
Enable again when activesupport 6.1 is released.
=> travis: Ignore Travis-CI failure for a while

.github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum.yml
Without name:, uses: is used by default.
=> CI: use meaningful action name

.github/workflows/apt.yml, .github/workflows/yum.yml
This pull request depends on #233.
=> Remove centos 6

README.md, td-agent/Gemfile, td-agent/Gemfile.lock, td-agent/Rakefile, td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/apt/ubuntu-xenial/Dockerfile, td-agent/msi/Dockerfile, td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile
bundler 2.2.0  has been released.
ref. https://rubygems.org/gems/bundler/versions/2.2.0
=> Use stable bundler release 2.2.0

td-agent/Rakefile
=> Remove centos-6 from default target list

td-agent/Gemfile.lock
=> Update protocol-http2 to 0.14.2

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/Gemfile.lock, td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/apt/ubuntu-xenial/Dockerfile, td-agent/config.rb, td-agent/msi/Dockerfile, td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/centos-stream-8/Dockerfile
It should be merged after #264
=> Use latest bundler

td-agent/Rakefile, td-agent/apt/commonvar.sh, td-agent/apt/ubuntu-hirsute/Dockerfile, td-agent/apt/ubuntu-hirsute/qemu-dummy-static
#267 should be merged beforehand.
=> Support Ubuntu 21.04 (Hirsute)

td-agent/msi/assets/td-agent.bat
=> Fix a typo in td-agent.bat

td-agent/templates/etc/init.d/td-agent.erb, td-agent/yum/td-agent.spec.in
Ported from https://github.com/treasure-data/omnibus-td-agent/pull/254
=> Remove redhad-lsb-core dependency

CHANGELOG.md
fix typo in release date for td-agent4.1.0
=> fix typo in release date for td-agent4.1.0

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/apt/binstubs-test.sh, td-agent/binstubs-test.rb, td-agent/yum/binstubs-test.sh
bundle binstubs --all --path ... should be exist on
/opt/td-agent/bin
=> Check whether binstubs is installed expectedly

td-agent/Rakefile, td-agent/config.rb
=> Apply the patch for resolv also on Windows

td-agent/Rakefile, td-agent/config.rb
=> jemalloc: Downgrade to 3.6.0 to reduce memory usage

td-agent/convert-artifacts-layout.sh
=> convert-artifacts-layout.sh: Don't skip AmazonLinux AArch64

td-agent/yum/opensuse-42/Dockerfile, td-agent/yum/opensuse-42/qemu-dummy-static, td-agent/yum/td-agent.spec.in
This is a trial if we can build it and whether it works for SLE
It may not be merged, anyway put it as a PR.
=> PoC: Support openSUSE

README.md, Rakefile, TODO.md, lib/yum/build.sh, td-agent/Rakefile, td-agent/config.rb, td-agent/msi/Dockerfile
td-agent-builder =>
fluent-package-builder
=> Follow changed repository name

td-agent/templates/opt/td-agent/share/td-agent.conf.tmpl
=> Enable minimum log rotation configuration for windows

td-agent/Gemfile, td-agent/Gemfile.lock
Closes #362 
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Bundle fluent-plugin-opensearch

.github/workflows/stale-actions.yml
Introduce action to close stale ones.
=> github: close stale issue/PR automatically

CHANGELOG.md, td-agent/config.rb, td-agent/debian/changelog, td-agent/yum/td-agent.spec.in
It's a bug fix release only for Windows platform.
=> v4.3.1.1 for Windows

td-agent/manage-fluent-repositories.sh
In addition, fix wrong usage in help.
=> manage-fluent-repositories.sh: Further automation of creating RPM repo

td-agent/Rakefile, td-agent/templates/etc/systemd/td-agent.erb, td-agent/templates/etc/systemd/td-agent.service.erb, td-agent/templates/package-scripts/td-agent/deb/postinst
Fix: https://github.com/fluent-plugins-nursery/fluent-package-builder/issues/352
=> Delete TD_AGENT_OPTIONS at td-agent.service

td-agent/yum/td-agent.spec.in
=> RPM: Add /etc/sysconfig/td-agent to td-agent.spec.in

td-agent/manage-fluent-repositories.sh
=> manage-fluent-repositories.sh: Fix wrong help document

CHANGELOG.md
=> CHANGELOG: Add OpenSSL to core components

td-agent/convert-artifacts-layout.sh
=> convert-artifacts-layout.sh: Drop xenial

td-agent/apt/pkgsize-test.sh, td-agent/yum/pkgsize-test.sh
=> Unlock package size comparision for recent distributions

.github/workflows/macos.yml, README.md, td-agent/Rakefile, td-agent/apt/debian-bullseye/Dockerfile, td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/apt/ubuntu-hirsute/Dockerfile, td-agent/apt/ubuntu-jammy/Dockerfile, td-agent/apt/ubuntu-xenial/Dockerfile, td-agent/msi/Dockerfile, td-agent/yum/almalinux-9/Dockerfile, td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/centos-stream-8/Dockerfile, td-agent/yum/rockylinux-8/Dockerfile
* Enable to build Apple Silicon binary of OpenSSL
* Update prerequisites for macOS
Fix #415
=> dmg: Support Apple Silicon

.github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/Rakefile, td-agent/yum/amazonlinux-2022-aarch64/from, td-agent/yum/amazonlinux-2022/Dockerfile, td-agent/yum/amazonlinux-2022/qemu-dummy-static, td-agent/yum/binstubs-test.sh, td-agent/yum/install-test.sh, td-agent/yum/pkgsize-test.sh, td-agent/yum/serverspec-test.sh, td-agent/yum/td-agent.spec.in
=> Support Amazon Linux 2022

fluentd-apt-source/Rakefile, fluentd-apt-source/debian/changelog, fluentd-apt-source/debian/control
Closes: #422 
TODO: deploy new deb.
=> deb: fix apt source priority

td-agent/Rakefile
File.exists? is removed as of Ruby 3.2
=> td-agent-v4: Replace File.exists? with File.exist?

fluent-package/convert-artifacts-layout.sh, fluent-package/manage-fluent-repositories.sh
Converting artifacts and updating repository feature is updated for 5.x.
=> Update utility scripts for fluent-package 5.x

CHANGELOG.md
I found some points to fix.
We need to add the same fix to master after this fix.
=> Fix CHANGELOG v4.5.0

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version.sh
=> apt: enable systemd service test again

fluent-package/convert-artifacts-layout.sh, fluent-package/manage-fluent-repositories.sh
* Add missing target to manage fluentd-apt-source
* Bump dry-download version to 5
* Add missing -architectures="all" for publishing only _all.deb
* Update supported platform for dry-upload
=> Tweak utility script for manage repository

fluent-package/yum/fluent-package.spec.in
rpm -qp --queryformat="%{Name}\n%{Summary}\n%{Description}" fluent-package/yum/repositories/centos/7/x86_64/Packages/fluent-package-5.0.0-1.el7.x86_64.rpm
fluent-package
All in one package of Fluentd
The stable distribution of Fluentd, formerly known as td-agent.
=> rpm: update spec description

fluent-package/apt/install-test.sh, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/install-test.sh
In the previous commit, useradd didn't set login shell
and home directory correctly.
=> Set system account (nologin) and home directory

fluent-package/Rakefile, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/binstubs-test.rb, fluent-package/convert-artifacts-layout.sh, fluent-package/debian/rules, fluent-package/msi/assets/fluent-package-version.rb, fluent-package/msi/build.bat, fluent-package/templates/etc/systemd/fluentd.erb, fluent-package/templates/etc/systemd/fluentd.service.erb, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/yum/fluent-package.spec.in
TODO: fluent-package/msi/assets/fluentd.bat must be fixed after c:\opt\td-agent migration. #494
=> Migrate TD_AGENT_ prefix to FLUENT_PACKAGE_

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/dmg/install-test.sh, fluent-package/msi/install-test.ps1, fluent-package/templates/etc/fluent/fluentd.conf, fluent-package/yum/install-with-systemd-test.sh
To solve the warning message:
Use different plugin for secondary ...
=> Use out_secondary_file for secondary output

fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/yum/fluent-package.spec.in
Expected result should be "If service is active ... then"
=> Fix inverted service control condition

fluent-package/convert-artifacts-layout.sh, fluent-package/manage-fluent-repositories.sh
Before:
./convert-artifacts-layout.sh apt
./convert-artifacts-layout.sh yum
After:
./convert-artifacts-layout.sh apt
./convert-artifacts-layout.sh yum
./convert-artifacts-layout.sh apt lts
./convert-artifacts-layout.sh yum lts
Then
artifacts/5 or artifacts/lts/5 will be used for output.
=> Support LTS related stuff to convert

fluent-package/manage-fluent-repositories.sh
It is aimed to allow snapshot packages in staging.
=> Allow to upload/download experimental channel

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/commonvar.sh, fluent-package/yum/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/test.sh
* deb rpm: verify to install the variants of apt-source
* rpm: follow repository layout for redhat variants
=> deb rpm: verify to install the variants of apt-source and .repo

fluent-package/yum/systemd-test/test.sh
Fix for a34d9704ac931d9b6d4d8c223ab6d2031c9b87f4 (#554)
=> yum: fix tests

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/install-newly.sh
As install script for fluent-package had been deployed, we will switch to it.
=> deb rpm: use latest install script

fluent-apt-source/debian/copyright, fluent-lts-apt-source/debian/copyright, fluent-package/templates/package-scripts/fluent-package/deb/copyright
* deb: fix Upstream-Name: field
* deb: fix path of licenses to /opt/fluent/LICENSES/
=> deb: fix upstream and path to licenses

.github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum.yml
Enable to use LTS branch's artifacts.
=> github: add missing LTS branch

CHANGELOG-v4.md
=> Add change log for td-agent v4.5.1

fluent-package/msi/Dockerfile
catch up latest version to reduce delta.
=> msi: use latest msys2

README.md
* Added fluent-package entry
* Dropped unsupported platform and introduced newly supported platform
=> Update obsolete explanation in README.md

CHANGELOG-v4.md
from 25010d7d455c7ddfde496d85b0a6f522acc6338d.
=> CHANGELOG: apply v4.5.2 release

.github/workflows/windows.yml, fluent-package/msi/assets/fluent-package-post-migration.bat, fluent-package/msi/update-from-v5-test.ps1
=> msi: stop migration run every update

CHANGELOG.md, fluent-package/Gemfile.lock, fluent-package/config.rb, fluent-package/debian/changelog, fluent-package/yum/fluent-package.spec.in
As LTS update, basically updates patch versions.
This is a maintenance release to patch version of Ruby.
=> fluent-package v5.0.4

.github/workflows/yum.yml, fluent-package/yum/rockylinux-8/Dockerfile
It should unify for consistency.
=> rpm: unify to short name

fluent-package/test-install-in-docker.sh
Not only test/experimental, test standard version and LTS too.
=> Allow to test more targets 5.x and 5.x (LTS)

CHANGELOG-v4.md
from e39937c4d9837eff8e0f9c86f57f48e96b80af41.
=> CHANGELOG: apply v4.5.3 release

fluent-package/templates/package-scripts/fluent-package/deb/preinst
Accidentally debug print in preinst was pushed in 26785ce.
=> deb: remove debug print

fluent-package/debug-package-converter.sh
It is useful to investigate maintainer scripts.
=> deb rpm: add helper script to repack debug packages

fluent-package/debug-package-converter.sh
Added if guard to check whether specified hook script exist or not.
=> deb: simplify helper script

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
see https://github.com/fluent/fluentd/pull/4689
ref. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> ci: add cancel-in-progress setting

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/yum/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
It would be better not to suppress the output for debugging.
=> ci: remove unnecessary option

.github/workflows/apt.yml, fluent-package/apt/systemd-test/update-from-v4.sh
Behavior may be different from installing from a deb file.
(Some tests should fail.)
=> ci: test deb migration from repository

fluent-package/debug-package-converter.sh
* enable debug by default
* support any package and architecture
* untabify
=> fluent-package: improve repack helper script

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/update-to-next-version-with-auto-and-manual.sh, fluent-package/yum/systemd-test/update-to-next-version-with-auto-and-manual.sh
add test to update with auto / manual feature.
=> ci: add test to update with auto / manual feature

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
see https://github.com/fluent/fluentd/pull/4689
ref. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
=> Backport: ci: add cancel-in-progress setting (LTS)

fluent-package/apt/systemd-test/update-to-next-version-without-data-lost.sh, fluent-package/yum/systemd-test/update-to-next-version-without-data-lost.sh
Update the test to ensure :
* There is no issue even if an upgrade is performed that includes a Ruby major version update.
* There is no data loss even if data is sent until the main process is replaced.
=> ci: update the tests for no data lost

fluent-package/yum/systemd-test/downgrade-to-v4.sh
This PR refactors the system-test code for RPM where it retrieves pid.
=> system-test: clean up a code where it retrieves pid

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/install-newly.sh
This PR will remove unnecessary condition for that it guards duplicated instance
=> system-test install-newly: remove unnecessary condition

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
This PR refactors the system-test code where it installs v4 packages.
=> system-test: clean up a code where it install v4 package

.github/workflows/maintenance-bundle-update.yml
This PR will add workflow due to create Pull Request for updated Gemfile.lock
Whe you run this workflow with manually, it will create PR like https://github.com/Watson1978/fluent-package-builder/pull/28
=> Add workflow to create Pull Request for updated Gemfile.lock

.github/workflows/apt.yml, .github/workflows/yum.yml
Ref. https://github.com/canonical/setup-lxd/releases/tag/v0.1.2
=> ci: update version of canonical/setup-lxd action

CHANGELOG.md
from https://github.com/fluent/fluent-package-builder/blob/fluent-package-v5/CHANGELOG.md#release-v505---20241108
=> CHANGELOG: apply v5.0.5

.github/workflows/windows.yml
This is backport 778 to v5 branch.
=> ci: add cache hash for msi (#778)

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/stale-actions.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
=> Backport github: use stable version of GitHub actions (#790)

fluent-package/manage-fluent-repositories.sh
In the previous versions, it download artifacts from GitHub in serial not parallel, so it takes huge amount of times.
In this version, it tries to download them in parallel, so it fixes above issue.
=> Backport: Enable parallel download artifacts (#768)

fluent-package/make-index-html.erb, fluent-package/make-index-html.rb
* Use latest REMIX ICON (Apache License 2.0)
* Add navigate to folders
* Add size in bytes
=> Revise index.html to browse them

.github/workflows/maintenance-bundle-update.yml
=> Backport: Maintenance workflow (#748)

.github/workflows/maintenance-bundle-update.yml
For LTS branch, it should not apply major,minor update in general.
=> ci: apply only patch release

.github/workflows/bundle-audit.yml
Not to let vulnerability alone, use bundle-audit
=> ci: apply bundle-audit

.github/workflows/bundle-audit.yml
Not to let vulnerability alone, use bundle-audit
=> Backport ci: apply bundle-audit (#838)

fluent-package/apt/commonvar.sh
openjdk-17 is not available anymore.
=> deb: update trixie JDK version

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/update-to-next-major-version.sh, fluent-package/apt/systemd-test/update-without-data-lost.sh, fluent-package/bump-version-v7.patch, fluent-package/config.rb, fluent-package/debian/changelog, fluent-package/msi/Dockerfile, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/update-from-v5-lts.sh, fluent-package/yum/systemd-test/update-to-next-major-version.sh, fluent-package/yum/systemd-test/update-without-data-lost.sh
This pull request move master branch to creating v6.0 package.
=> Move to v6.0.0

fluent-package/manage-fluent-repositories.sh
v7 package is only for test purpose.
Must not ship it.
=> Do not download needless v7 test package

fluent-package/convert-artifacts-layout.sh
* Drop AmazonLinux 2
* Support AlmaLinux 10 (redhat/10)
=> Follow layout converter

fluent-package/manage-fluent-repositories.sh
There is a case that the response of API doesn't match expected pull request.
As a result, it must follow the next one or more to search.
=> Backport: Improve utility script not to fail with empty response (#888)

.github/workflows/apt.yml
images:ubuntu/20.04 is not available anymore, so
trying to use custom Incus image.
=> deb: try to use custom fluent image
