lib/apt/build.sh, td-agent/debian/lintian/td-agent/debian.profile
Related to #4.
I didn't create custom lintian profile for Ubuntu but this script also considers for it.
`td-agent/debian/lintian/td-agent/ubuntu.profile` should be used in Ubuntu docker build environment.
=> Override opt dir lintian errors with custom td-agent-builder profile

td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-6/qemu-dummy-static
CentOS 6 doesn't support armv8.
So, we needn't prepare armv8/centos:6 Dockerfile.
Follows up #19.
Sorry, I'd forgotten to add Dockerfile which is used on CentOS 6 package building.... :cold_sweat:
=> Add CentOS 6 Dockerfile

td-agent/yum/td-agent.spec.in
Reverts clear-code/td-agent-builder#25
It's my misuderstanding,  dependencies are automatically resolved.
I just forgot to enable EPEL:
$ sudo dnf install epel-release -y
=> Revert "RPM: Add missing dependencies"

td-agent/Rakefile, td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/config.rb, td-agent/debian/control, td-agent/templates/etc/init.d/td-agent.erb, td-agent/templates/etc/systemd/td-agent.service.erb, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/td-agent.spec.in
This commit discards "--with-jemalloc" option of Ruby, it seems hard to
use with libjemalloc in non-standard directory. Revive LD_PRELOAD
instead.
Fix #29
=> Bundle jemalloc

td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/td-agent.spec.in
Related to #31.
These are for libsasl2.so and libfreebl3.so.
CentOS 6 and 7 can handle linking libfreebl3 against librdkafka.so, but CnetOS 8 cannot handle it.
Should we fix ti?
```
Installed:
td-agent-3.7.0-1.el8.x86_64                                       libzstd-1.4.4-1.el8.x86_64                                      
Complete!
[vagrant@localhost Packages]$ ldd /opt/td-agent/lib/ruby/gems/2.4.0/gems/rdkafka-0.7.0/ext/librdkafka.so
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (ja_JP.UTF-8)
linux-vdso.so.1 (0x00007ffc14fea000)
liblz4.so.1 => /lib64/liblz4.so.1 (0x00007fb95c1ce000)
libm.so.6 => /lib64/libm.so.6 (0x00007fb95be4c000)
libzstd.so.1 => /lib64/libzstd.so.1 (0x00007fb95bba8000)
libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fb95b98a000)
libssl.so.1.1 => …
```
=> yum: Add missing cyrus-sasl-devel and nss-softkn-freebl-devel build dependencies

td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/td-agent.spec.in
zstd and lz4 are provided from EPEL.
They should be removed from building environment and dependencies.
Related to https://github.com/clear-code/td-agent-builder/pull/24#issuecomment-614111428.
=> yum: Remove EPEL dependecies

td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/debian/control
Related to #31.
We also should remove zstd and lz4 dependencies from apt platforms.
=> apt: Remove zstd and lz4 dependencies

td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/td-agent.spec.in
Related to #31.
* libedit
* libtinfo
* libyaml
libxml2 and liblzma shouldn't be needed. Because we don't bundle nokogiri gem.
=> yum: Add more dpendent libraries

td-agent/debian/control
It fixes E: td-agent: extended-description-is-empty
lintian error.
=> deb: add missing extended-description

lib/apt/build.sh
It fixes E: td-agent changes: bad-distribution-in-changes-file
unstable lintian error.
=> deb: set correct distribution in changelog

td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/debian/control
cdbs is not used in d/rules at all.
It fixes W: td-agent source: unused-build-dependency-on-cdbs
NOTE: cdbs is referenced from autotools indirectly,
(td-agent itself does not depends it directly)
So, cdbs is only still listed in Dockerfile.
=> deb: drop needless Build-Depends

td-agent/debian/td-agent.lintian-overrides
It is false posivive because of /tmp/td-agent is
accessed by only td-agent:td-agent user/group.
=> deb: fix td-agent tmp files handling in postinst

td-agent/debian/rules
dh_makeshlibs kicks unnecessary ldconfig triggers, so
it is suppressed by override_dh_makeshlibs.
=> deb: fix package-has-unnecessary-activation-of-ldconfig-trigger

td-agent/Rakefile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/td-agent.spec.in
refs:
* https://github.com/clear-code/td-agent-builder/issues/44
* https://fedoraproject.org/wiki/Packaging:Debuginfo
* https://bugs.ruby-lang.org/issues/12934
* https://docs.fedoraproject.org/en-US/packaging-guidelines/#_beware_of_rpath
* https://fedoraproject.org/wiki/Changes/Make_ambiguous_python_shebangs_error
=> RPM: Build debuginfo package to strip executables

td-agent/debian/td-agent.lintian-overrides
It fixes W: maintainer-script-should-not-use-recursive-chown-or-chmod.
In postinst script, permission should be changed explicitly
to mitigate hardlink attacks.
=> deb: don't use recursive chown

td-agent/debian/td-agent.lintian-overrides
These files are just templates.
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable #!<%=
W: td-agent: unusual-interpreter opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.bundler #!<%=
W: td-agent: unusual-interpreter
opt/td-agent/lib/ruby/gems/2.4.0/gems/bundler-1.16.6/lib/bundler/templates/Executable.standalone
#!<%=
=> deb: suppress false positive W: td-agent: unusual-interpreter

td-agent/debian/td-agent.lintian-overrides
ref. https://www.debian.org/doc/debian-policy/ch-files.html#scripts
It should be fixed in jemalloc upstream.
=> deb: suppress W: incorrect-path-for-interpreter

td-agent/Rakefile, td-agent/templates/package-scripts/td-agent/deb/copyright
It follows https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
=> deb: add missing copyright

td-agent/Rakefile
This commit fixes the following lintian warning:
W: td-agent source: missing-license-paragraph-in-dep5-copyright apache license version 2.0 (paragraph at line 128)
W: td-agent source: space-in-std-shortname-in-dep5-copyright apache license version 2.0 (paragraph at line 128)
ref. https://spdx.org/licenses/
=> deb: fix spdx incompatible license field

td-agent/Rakefile, td-agent/debian/td-agent.lintian-overrides
It fixes E: td-agent: incorrect-libdir-in-la-file
No need to override td-agent: incorrect-libdir-in-la-file
in td-agent.lintian-override anymore.
=> deb: remove needless .la files

td-agent/Rakefile, td-agent/debian/td-agent.lintian-overrides
It fixes W: td-agent: package-contains-vcs-control-file lintian
warnings.
No need to override td-agent: package-contains-vcs-control-file
in td-agent.lintian-override anymore.
=> deb: remove needless vcs control file

td-agent/debian/td-agent.lintian-overrides
It seems that td-agent: dir-or-file-in-build-tree is not used.
=> deb: remove unused override rule

td-agent/debian/td-agent.lintian-overrides
Since dpkg 1.15.7.2, conffile handling is improved,
but to keep compatibility, update_conffile is still needed as is.
=> deb: suppress postinst warnings

td-agent/apt/ubuntu-focal-arm64/from
I tested this patch with https://github.com/clear-code/td-agent-builder/pull/24 and build stops by lintian phase.
Does anyone check this patch?
=> Add arm64 support to ubuntu focal

td-agent/yum/td-agent.spec.in
It should be ASL 2.0 instead of Apache-2.0
ref. https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Software_License_List
=> rpm: fix licence field

lib/apt/build.sh, lib/package-task.rb
There is a case that lintian check stalls on ubuntu focal
arm64. Until that issue is fixed, skip lintian check as
a workaround.
Closes: #66
=> deb: support to skip lintian

td-agent/plugin_gems.rb
Bump up the version to 0.7.4.
See also: https://github.com/fluent-plugins-nursery/winevt_c/pull/26
Fix #26
=> Fix build error of winevt_c

td-agent/yum/td-agent.spec.in
It seems that ", called td-agent" is redundant.
td-agent.x86_64: W: name-repeated-in-summary C td-agent
The name of the package is repeated in its summary.  This is often redundant
information and looks silly in various programs' output.  Make the summary
brief and to the point without including redundant information in it.
=> rpm: fix W: name-repeated-in-summary

td-agent/yum/td-agent.spec.in
.logrotate suffix is removed at
8c9dc8d66080f6c77148fab49d0bebf8f2b867cf.
=> rpm: Fix the wrong path of the logrotate config file

td-agent/yum/td-agent.spec.in
Install man section(1) pages and compress them.
=> rpm: fix W: no-manual-page-for-binary

td-agent/yum/rpmlint.config
It is ok suppressing E: postin-without-ldconfig and E:
library-without-ldconfig-postun because /opt/td-agent was isolated
with packages which are installed to the system.
=> rpm: suppress error without ldconfig

td-agent/Rakefile
It fixes:
W: spurious-executable-perm /opt/td-agent/lib/libjemalloc.a
W: spurious-executable-perm /opt/td-agent/lib/libjemalloc_pic.a
=> rpm: remove needless static library

td-agent/yum/td-agent.spec.in
The previous patterns like "*.1" or "*.3" are too rough, they also match
libruby.so.2.7.1 unexpectedly.
=> rpm: Don't compress non-man files

td-agent/Rakefile
remove_files("ext/**/*.{o,la,a}") removes *.o,*.la,*.a, but
not for .libs/*.o, .libs/*.la, .libs/*.a so explicitly removes
.libs directory.
=> rpm: remove .libs explicitly

td-agent/yum/amazonlinux-2/Dockerfile
Otherwise, executing rpmlint on Amazon Linux causes command not found error.
=> Run rpmlint on Amazon Linux 2

td-agent/templates/usr/lib/tmpfiles.d/td-agent.conf, td-agent/yum/td-agent.spec.in
It fixes: E: dir-or-file-in-var-run.
On CentOS 6, tmpfiles.d is not avairable, so to keep these directory,
create special file under such a directory.
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
=> rpm: use tmpfiles.d for /var/run/td-agent/

README.md, td-agent/Rakefile
This will be fixing #98.
And this patch is inspired by https://github.com/treasure-data/omnibus-td-agent/blob/05a1f1a43732383828f4cbec47e393773c14acea/config/software/ruby.rb#L296-L323.
=> Find and copy libstdc++-6.dll from building system

td-agent/yum/rpmlint.config
Under /usr/lib/*, systemd or tmpfiles.d configuration
files are put.
=> rpm: fix W: only-non-binary-in-usr-lib on CentOS 7

td-agent/yum/rpmlint.config
In /etc/init.d/td-agent, rpmlint reports /var/lock/subsys is
incoherent.
It seems that TD_AGENT_LOCK_FILE="/var/lock/subsys/${prog}" in
/etc/init.d/td-agent is regarded as incoherent because
it is not /var/lock/subsys/td-agent. Thus it is false positive.
=> rpm: fix W: incoherent-subsys

td-agent/plugin_gems.rb
It fixes the issue that rc version of nokogiri (1.11 rc2) which supports ruby 2.7.1
is not installed
ref. https://github.com/sparklemotion/nokogiri/issues/2029
=> Use latest fluent-plugin-windows-eventlog

td-agent/Rakefile, td-agent/msi/parameters.wxi.erb
Wix using package version should be modified into buildable version number.
This is one of the possible prerelease version implementation.
=> Use WiX makable release candidate version

td-agent/Rakefile
Additionally, build time (hour) is also considered
for CI.
~rc1: x.x.x.10009 if ~rc1 is built at 9am
~beta1: x.x.x.1009  if ~beta1 is built at 9am
~alpha1: x.x.x.109   if ~alpha1 is built at 9am
=> Support ~alphaN, ~betaN, and ~rcN version

td-agent/plugin_gems.rb
We should bundle fluent-plugin-parser-winevt_xml to parse XML style Windows EventLog events.
This should be needed for restoring previous version omnibus-td-agent installer behavior.
=> Bundle fluent-plugin-parser-winevt_xml plugin

lib/apt/build.sh
At least, Ubuntu Bionic and Focal renames dbgsym debian packages' extension to ddeb from deb.
We should copy them into package pool.
=> apt: Add ddeb copying targets

td-agent/debian/copyright, td-agent/plugin_gems.rb
Using nokogiri 1.11.0.rc2 is first aid to build with Ruby 2.7 on Windows.
We should use the stable version of nokogiri 1.10.10.
=> Use nokogiri 1.10.10

td-agent/templates/opt/td-agent/share/td-agent.conf.tmpl
On windows, /var/... may creates C:/var, so it should be
ENV['TD_AGENT_TOPDIR'] (typically c:/opt/td-agent) prepended.
=> MSI: Use ENV['TD_AGENT_TOPDIR'] to specify install directory

td-agent/msi/source.wxs
In the previous version (4.0.0), we need start
Fluentd Windows Service(fluentdwinsvc) manually.
In this commit, use delay start which is supported in Fluentd 1.11.1.
=> MSI: support to enable delay start

td-agent/Rakefile
https://github.com/ruby/ruby/blob/ruby_2_7/NEWS#label-Stdlib+updates+-28outstanding+ones+only-29
Signed-off-by: Kohei Suzuki <eagletmt@gmail.com>
=> Use URI.open instead of deprecated Kernel#open

td-agent/Rakefile, td-agent/templates/package-scripts/td-agent/deb/prerm
It is useless because of source confmodule doesn't affects package
behavior.
=> deb: drop needless prerm

td-agent/debian/td-agent.lintian-overrides
It is caused by installing /opt.
=> deb: suppress lintian errors

.travis.yml
This is because network error sometimes occurs in Travis.
This command should retry build step when error occurred.
But `travis_retry` is not perfect solution for #136. 
This seems to be Travis' network problem...:
```
ERROR:  Could not find a valid gem 'fluent-plugin-systemd' (= 1.0.2), here is why:
Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/quick/Marshal.4.8/fluent-plugin-systemd-1.0.2.gemspec.rz)
ERROR:  Possible alternatives: fluent-plugin-systemd
ERROR:  Could not find a valid gem 'fluent-plugin-systemd-1.0.2.gem' (>= 0) in any repository
```
ref: https://travis-ci.com/github/fluent-plugins-nursery/td-agent-builder/jobs/361133664#L1039
=> travis: Try to use travis_retry

td-agent/core_gems.rb
Otherwise, when using Ruby 2.7, users get the following warnings:
<details>
```
~/Documents/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:333: warning: rb_check_safe_obj will be removed in Ruby 3.0
~/Documents/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:333: warning: rb_check_safe_obj will be removed in Ruby 3.0
~/Documents/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:333: warning: rb_check_safe_obj will be removed in Ruby 3.0
~/Documents/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:333: warning: rb_check_safe_obj will be removed in Ruby 3.0
~/Documents/GitHub/fluentd/vendor/bundle/ruby/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:350: …
```
=> Use win32-api v1.9.1

td-agent/templates/package-scripts/td-agent/deb/postinst
Closes: #145
Since TD Agent 4.0.0, tmpl path was changed from
/etc/td-agent/td-agent.conf.tmpl.
It is a good manner not to put .tmpl under /etc, but
path of new .tmpl is not updated.
It caused a bug that re-install package fails because of
the following error:
Updating conffile /etc/td-agent/td-agent.conf ...
cp: cannot stat '/etc/td-agent/td-agent.conf.tmpl': No such file or directory
dpkg: error processing package td-agent (--configure):
installed td-agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
td-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
=> deb: update tmpl path

td-agent/Rakefile
This patch also prevent to create nested opt directory on msi package.
Fixes #150.
Closes #156 in favor of this PR.
=> msi: Prevent to generate needless files on Windows

td-agent/Rakefile, td-agent/msi/source.wxs
Use TD_AGENT_TOPDIR in td-agent.conf on Windows
which is generated from .tmpl file.
and logrotate.d is not needed, so it was removed
NOTE: Alter installed at once, TD_AGENT_TOPDIR
is not refrected immediately.
=> MSI: set TD_AGENT_TOPDIR correctly

td-agent/msi/source.wxs
Before:
-c opt\\td-agent\\\\etc\\td-agent\\td-agent.conf
-o opt\\td-agent\\\\td-agent.log
After:
-c opt\\td-agent\\etc\\td-agent\\td-agent.conf
-o opt\\td-agent\\td-agent.log
=> MSI: remove needless separator

README.md
Ubuntu 20.04 and 16.04 are also built by default.
=> Update default apt targets list

td-agent/Rakefile
Closes: #176
Arm64 with Ubuntu/AL2 and x86_64 with all OSes use 4096 page size but
Arm64 with CentOS uses 65536 page size.
So, by specifying --with-lg-size=16, explicitly set PAGE_SIZE=65536
on such environment.
This commit fixes the following errors.
fluentd[15556]: <jemalloc>: Unsupported system page size
fluentd[15556]: <jemalloc>: Unsupported system page size
fluentd[15556]: [FATAL] failed to allocate memory
=> rpm: set PAGE_SIZE=65536 on CentOS 7/8 aarch64

.github/workflows/macos.yml, lib/gems_parser.rb, td-agent/Rakefile
We'll create macOS package for Homebrew Formula or macOS installer (pkg/dmg).
So, the first step is `rake build:all` on macOS worker of GitHub Actions.
=> macOS: Prelimitary build on GitHub Actions

td-agent/Rakefile
config.rb is required from Gemfile and Gemfile is put
under /opt/td-agent/share/Gemfile. The path must be adjusted.
=> Add config.rb with rewritten "require" path in Gemfile

README.md
Update Ruby requirement to 2.5 because 2.4 series are not supported
anymore and to use multiplatform feature, Bundler 2.2.0.rc.1 is
required.
=> Update requirement about ruby and bundler

td-agent/Rakefile
bundle command assumes that "path" is writable, so
if you use system's ruby, it requires sudo without
path configuration.
Closes: #194
=> Suppress privilege escalation (sudo) when executing bundle command

.github/workflows/apt.yml
--privileged is required to debootstrap command, so
It is no need to specify for install test/serverspec test cases.
=> CI: remove needless --priviledged

lib/apt/build.sh
In the previous version, .bundle/config is contained in git
repository.
Therefore, .bundle/config was rewritten, so --auto-commit is used to
ignore changes during build process.
Currently, .bundle/config is removed from git repository, so
there is no need to use --auto-commit.
=> deb: remove needless auto-commit

td-agent/Rakefile
This commit fixes W: cross-directory-hard-link rpmlint warning
=> rpm: remove needless .git directory

.github/workflows/apt.yml
`with` clause should be same indentation level for `uses` or `name`
Otherwise, apt workflow is broken.... :cry:
=> github: apt: Fix an indentation on apt workflow

td-agent/msi/serverspec-test.ps1
Specinfra v2.82.20 includes this change:
https://github.com/mizzy/specinfra/commit/73ee0f20ad9f1484da2865ba53945f7563119cb5
=> td-agent: msi: serverspec: Remove find_installed_gem.ps1 workaround

td-agent/templates/usr/sbin/td-agent.erb
Example:
$ /usr/sbin/td-agent --version
td-agent 4.0.1 fluentd 1.11.2 (2f80f6cf0a4aa44b9795cd6a66894a6b8fa70d06)
=> deb rpm: show td-agent and fluentd version at the same time

td-agent/Rakefile, td-agent/msi/assets/td-agent-version.rb, td-agent/msi/assets/td-agent.bat
Example:
> .\td-agent.bat --version
td-agent 4.0.1 fluentd 1.11.2 (2f80f6cf0a4aa44b9795cd6a66894a6b8fa70d06)
=> msi: show td-agent and fluentd version

td-agent/yum/rpmlint.config
Amazon Linux 2's rpm lint complains the following:
<details>
```
td-agent.x86_64: W: non-standard-uid /etc/td-agent/plugin td-agent
A file in this package is owned by a non standard user. Standard users are:
abrt, activemq, adm, aeolus, amandabackup, apache, arpwatch, ats, avahi,
avahi-autoipd, bacula, beagleindex, bin, ceilometer, ceph, cimsrvr, cinder,
clamav, condor, cyrus, daemon, dbus, desktop, dhcpd, distcache, dovecot,
elasticsearch, exim, fax, frontpage, ftp, games, gdm, glance, gopher,
hacluster, haldaemon, halt, haproxy, heat, hsqldb, ident, jboss, jbosson-
agent, jetty, jonas, katello, keystone, ldap, lp, luci, mail, mailman,
mailnull, majordomo, mongodb, myproxy, mysql, named, netdump, news, nfsnobody,
nobody, nocpulse, nova, nscd, nslcd, ntp, nut, operator, oprofile, ovirt, …
```
=> amazonlinux-2: Suppress non-standard-uid/gid warnings

td-agent/yum/centos-8/Dockerfile, td-agent/yum/install-test.sh, td-agent/yum/serverspec-test.sh
e.g.
```
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:04:39 ago on Mon Dec 14 05:37:32 2020.
=================================================== Name Exactly Matched: libedit-devel ====================================================
libedit-devel.i686 : Development files for libedit
libedit-devel.x86_64 : Development files for libedit
```
=> centos8: use correct repo name

.github/workflows/windows.yml, td-agent/msi/Dockerfile
We need to install bundler before entering building process on Windows.
=> Fix Windows Action

.github/workflows/yum.yml, lib/yum/build.sh, td-agent/apt/serverspec-test.sh, td-agent/yum/centos-stream-8/Dockerfile, td-agent/yum/centos-stream-8/qemu-dummy-static, td-agent/yum/install-test.sh, td-agent/yum/serverspec-test.sh
confluent-community 2.13 supports CentOS/RHEL 8.
I also enabled CentOS/CentOS Stream 8 kafka test on serverspec.
=> Create CentOS Stream 8 package and GitHub Actions

.github/workflows/apt.yml, .github/workflows/yum.yml, td-agent/Rakefile
It fixes the follwing error:
https://github.com/fluent-plugins-nursery/td-agent-builder/runs/1586326203
Failed to download gem files: <bundle package --no-install> (output: You must use Bundler 2 or greater with this lockfile.
, error: )
/home/runner/work/td-agent-builder/td-agent-builder/td-agent/Rakefile:1113:in `block in build_include_binaries_file'
/home/runner/work/td-agent-builder/td-agent-builder/td-agent/Rakefile:1109:in `chdir'
/home/runner/work/td-agent-builder/td-agent-builder/td-agent/Rakefile:1109:in `build_include_binaries_file'
/home/runner/work/td-agent-builder/td-agent-builder/td-agent/Rakefile:1037:in `block in define_archive_task'
Tasks: TOP => apt:build => td-agent-4.0.1.tar.gz => td-agent/debian/source/include-binaries
(See full trace by running task with --trace) …
=> CI: Install bundler 2.2.0 to build td-agent for GNU/Linux platforms

td-agent/msi/source.wxs
Closes: #3201
Reported by @zubrahzz
ref. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28169
In the previous version, NT AUTHORITY\Authenticated Users:(I)(M) is
granted. It means that logged in users can replace any files under
opt/td-agent/bin. It also allows for attacker to gain administrative
privileges by replacing these files because these files are executed
as a local services with SYSTEM privilege.
Note that this PR was merged, we need to update gems
by td-agent-gem with administraror privilege.
=> windows: mitigate possible escalation of privileges

td-agent/Rakefile
Although the working directory on installing gems is
BUILDROOT\td-agent, the cache path is set to td-agent/download
so the resolved absolute path includes redundant "td-agent".
As a result pre-downloaded gems aren't used, they are downloaded
again unexpectedly.
=> Fix wrong cache path of bundler on installing gems

td-agent/Gemfile, td-agent/Gemfile.lock, td-agent/Rakefile
Fixed version has been released:
https://rubygems.org/gems/protocol-http2/versions/0.14.2
=> Remove a workaround for broken protocol-http2

td-agent/Rakefile
For https://github.com/fluent-plugins-nursery/td-agent-builder/pull/248#issuecomment-771270276
=> Remove bundler's cache files that are Git origin

td-agent/Gemfile, td-agent/Rakefile, td-agent/config.rb
Previous code uses `gem install` to install gems so that it ignores gem's versions described in Gemfile.lock. Because we are now using Gemfile, there is no reason not to use bundler to install gems.
In addition, this PR also prevent to install mismatched architecture's gem even if a source taball is created by a host OS that is different from a target.
=> Use bundler to install gems

td-agent/Rakefile
The size of windows installer is decreased from 35MB to 26MB.
=> Remove needless ri documents in RubyInstaller (as of 2.7.2-1)

td-agent/Gemfile
As CI had been migrated into GitHub Actions, it should be removed.
=> CI: remove unused Travis related gem

td-agent/Gemfile, td-agent/Gemfile.lock
Because of Ruby 3.0 dropped it.
=> Explicitly install webrick 1.7.0

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/apt/ubuntu-focal/Dockerfile, td-agent/apt/ubuntu-xenial/Dockerfile, td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/centos-stream-8/Dockerfile
If IPv6 is preferred in container, we can not
connect to rubygems.org. it causes timeout error.
=> Raise IPV4 priority for connecting rubygems.org

td-agent/yum/td-agent.spec.in
The following libraies that provided by td-agent 4 conflict with system's one:
* libjemalloc.so.2()(64bit)
* librdkafka.so.1()(64bit)
* libruby.so.2.7()(64bit)
All shared libraries under /opt/td-agent/ should be ignored.
Otherwise td-agent may be installed unexpectedly when a package that requires these libraries is installed.
=> RPM: Remove conflicted `provides` libraries

td-agent/yum/amazonlinux-2/Dockerfile, td-agent/yum/centos-6/Dockerfile, td-agent/yum/centos-7/Dockerfile, td-agent/yum/centos-8/Dockerfile, td-agent/yum/centos-stream-8/Dockerfile
The value of priority is not set correctly.
This affects the access timeout to rubygems.org during build on IPv6 preferred
host.
=> yum: raise IPv4 priority correctly

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
Avoid following error on build_include_binaries_file
> stderr: Could not find fileutils-1.5.0.gem for installation
TODO: Should succeed to download it even if system's one exists
=> CI: Remove installed fileutils gem before downloading gems

td-agent/msi/pkgsize-test.ps1
to fix  https://github.com/fluent-plugins-nursery/td-agent-builder/issues/278
@ashie , fyi
=> fix ci for windows, use heroku uri to check instead

td-agent/Rakefile, td-agent/yum/td-agent.spec.in
Because it depends on glibc 2.17 which doesn't exist in CentOS 6.
=> Work arround to avoid installing fat gem of nokogiri 1.11 on CentOS 6

td-agent/yum/td-agent.spec.in
5c905844edf9e4a2db556ef9ba16f4e3c4ea9c76 lacks filters for provides.
=> Remove needless dependencies on RHEL/CentOS 6, again

lib/package-task.rb
Otherwise, the current implementation will handle wrongly for
centos-stream-8-aarch64 target case:
```console
docker build --tag custom-fluentd-centos-stream-8-aarch64 --build-arg \
DEBUG=yes --build-arg FROM=arm64v8/centos:8 centos-stream
```
This can cause the following error:
```log
docker build --tag custom-fluentd-centos-stream-8-aarch64 --build-arg DEBUG=yes --build-arg FROM=arm64v8/centos:8 centos-stream
unable to prepare context: path "centos-stream" not found
rake aborted!
Command failed with status (1): [docker build --tag calyptia-fluentd-centos...]
/media/Data2/Gitrepo/custom-fluentd-builder/lib/package-task.rb:148:in `run_docker'
/media/Data2/Gitrepo/custom-fluentd-builder/lib/package-task.rb:346:in `block (2 levels) in yum_build' …
```
=> package-task: Handle centos-stream-8-aarch64 yum target properly

td-agent/msi/source.wxs
Reported via https://github.com/fluent/fluentd/issues/3322
For example, there is a case that the required account is not created by
non-english platforms. It depends on localization.
Instead, it may be better to use well-known ACEs in SDDL.
ref. https://docs.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-definition-language-for-conditional-aces-
=> msi: fix uninstallable binary on non-English

td-agent/apt/commonvar.sh
This causes unbound variable error on using ubuntu:firsute image.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Fix wrong Ubuntu 21.04 codename

td-agent/templates/etc/systemd/td-agent.service.erb
Fix the following error:
Apr 27 01:27:04 localhost.localdomain systemd[1]: /usr/lib/systemd/system/td-agent.service:3: Failed to resolve unit specifiers in ''https://docs.treasur>
=> Escape % in td-agent.service

td-agent/Rakefile
* Add amazonlinux-2
* Remove ubuntu-hirsute, because it's not LTS
=> Tweak default target platforms

td-agent/apt/serverspec-test.sh
As apt-key will be removed in Debian 12, it is not recommended to use
apt-key. The replacement of apt-key is using /etc/apt/trusted.gpg.d/
keyring instead.
NOTE: GnuPG 2.x new keyring format (keybox) is not recognized, we need
to use legacy public ring v4.x for a moment.
See
https://www.debian.org/releases/testing/amd64/release-notes/ch-information.en.html#obsolescense-and-deprecation
=> apt: drop apt-key from test script

td-agent/convert-artifacts-layout.sh
td-agent-builder is aimed to build packages under
apt/repository/DIST/pool/RELEASE/ or yum/repository/DIST/RELEASE/, but
packages.tresuredata.com adopts a bit different repository layout.
This script collects release packages and put them to
td-agent/repository/4/.
=> apt yum: add script to collect packages for packages.treasuredata.com

td-agent/config.rb, td-agent/patches/ruby-3.0/0001-ruby-resolv-Fix-confusion-of-received-response-messa.patch
See following links for more detail:
* https://bugs.ruby-lang.org/issues/17748
* https://github.com/fluent/fluentd/issues/3382
The patch for Ruby is taken from the following commit:
https://github.com/ruby/ruby/commit/9edc162583a4f685332239f6249745ad9b518cbe
=> Fix a bug that fluentd gets stuck on DNS lookup due to resolv's bug

td-agent/Gemfile.lock
See https://github.com/advisories/GHSA-hj56-84jw-67h6
CVE-2021-32823
Vulnerable versions: < 2.4.10
Patched version: 2.4.10
=> Update bindata to 2.4.10

td-agent/Rakefile
If Psych backend v4.0.0 or later is used for YAML, it fails to load
because of incompatibility of YAML.load.
For example, it causes the following error.
```
cd td-agent
/home/kenhys/.rvm/rubies/ruby-2.7.3/bin/ruby -S rake apt:build
rake aborted!
Psych::DisallowedClass: Tried to load unspecified class: Gem::Specification
/home/kenhys/.rvm/gems/ruby-2.7.3@fluentd-test/gems/psych-4.0.1/lib/psych/class_loader.rb:99:in `find'
/home/kenhys/.rvm/gems/ruby-2.7.3@fluentd-test/gems/psych-4.0.1/lib/psych/class_loader.rb:28:in `load'
```
As it is known that what class will be actually loaded, it should use
YAML.safe_load and permit class explicitly.
This fix is compatible with Psych v3.x and v4.x.
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
=> Use YAML.safe_load explicitly

td-agent/Rakefile
It won't be used in production environments.
And it introduces unnecessary dependencies.
Fix #306
=> Remove jeprof

lib/yum/build.sh
os-release is machine readable and contains consistent identification
data.
ref. https://www.freedesktop.org/software/systemd/man/os-release.html
=> rpm yum: use os-release

td-agent/yum/td-agent.spec.in
It makes maintenance easy
NOTE: _suse_ver >= 1315 means openSUSE/leap 42.3 or later.
Thus, it also means that SLES 12 or later because openSUSE 42.3 is
compatible with SLES 12.
=> rpm: use use_suse for consistency

td-agent-apt-source/apt/debian-bullseye/Dockerfile, td-agent/apt/commonvar.sh, td-agent/apt/debian-bullseye-arm64/from, td-agent/apt/debian-bullseye/Dockerfile, td-agent/apt/debian-bullseye/qemu-dummy-static
Debian 11 "bullseye" released
https://www.debian.org/News/2021/20210814
=> deb: support Debian 11 (bullseye)

td-agent/templates/package-scripts/td-agent/deb/postinst
Since td-agent 4.0.0, td-agent.conf.tmpl was moved from
/etc/td-agent/td-agent.conf.tmpl to
/opt/td-agent/share/td-agent.conf.tmpl.
It means that td-agent.conf.tmpl was not registered in
Conffiles: entries anymore. (It's not under /etc)
Then, old_md5sum becomes always empty, backward compatibility
is triggered.
```
Unpacking td-agent (4.2.0-1) over (4.1.1-1) ...
Setting up td-agent (4.2.0-1) ...
Updating conffile /etc/td-agent/td-agent.conf ...
Processing triggers for man-db (2.9.4-2) ...
```
As a result, td-agent.conf file will be overridden. (It's no
harm because the content is same.)
In this commit, check template file checksum correctly.
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
=> deb: remove needless update conf hook

td-agent/msi/assets/td-agent-version.rb
Require rubygems to find correct fluent/version.rb
Otherwise `td-agent --version` causes following error because `bundler`
directory doesn't exist anymore:
C:/opt/td-agent/bin//../bin/td-agent-version.rb:6:in `<main>': uninitialized constant Fluent (NameError)
=> MSI: Get fluentd version correctly

td-agent/msi/install-test.ps1
Since log rotation is introduced at #343, a number suffix is added to
log file name.
td-agent.log ->
td-agent-0.log
=> MSI: Fix log file name in install-test

.github/workflows/apt-arm.yml
qemu-user-static on Ubuntu 20.04 contains a bug that crashes arm64
Debian Bullseye guests:
https://bugs.launchpad.net/qemu/+bug/1749393
This patch works around that issue, by installing the required qemu
binaries (in particular `qemu-aarch64-static`) using
"multiarch/qemu-user-static" image.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Fix build error on Debian Bullseye

td-agent/yum/rockylinux-8-aarch64/from, td-agent/yum/rockylinux-8/Dockerfile, td-agent/yum/rockylinux-8/qemu-dummy-static
It stores RPMs under td-agent/yum/repositories/centos for
compatibility.
TODO: support armv64v8/rockylinux:8 as well. It is not accessible from my
environment :-<, It will be handled in another PR.
=> yum: use rockylinux as base build image

.github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/yum/binstubs-test.sh, td-agent/yum/install-test.sh, td-agent/yum/pkgsize-test.sh, td-agent/yum/serverspec-test.sh
CentOS 8 had reached already EOL, so just replace it with an alternative base build image for RHEL.
=> Drop centos8 and use alternative image

.github/workflows/windows.yml, td-agent/Rakefile, td-agent/msi/Dockerfile
Try to fix the following error:
```
Failed to download gem files: <bundle package --no-install> (stdout: Fetching gem metadata from https://rubygems.org/...........
Fetching https://github.com/fluent/fluentd
, stderr: Warning: the running version of Bundler (2.2.9) is older than the version that created the lockfile (2.2.32). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.32`.
nokogiri-1.13.1-x64-mingw32 requires ruby version < 3.1.dev, >= 2.6, which is
incompatible with the current version, ruby 2.5.9p229
```
=> CI: Fix build error on Windows

.github/workflows/yum.yml, td-agent/yum/centos-8/Dockerfile, td-agent/yum/centos-stream-8/Dockerfile
* CI: Stop running centos-stream-8
* Replace dnf repository URLs to keep them buildable
We don't use them anymore but keep them for a while for reference.
=> Tweak CentOS 8 containers

lib/apt/build.sh, lib/yum/build.sh, td-agent/Rakefile
Due to CVE-2022-24765, Git 2.35.2 or later cannot run any command when
the paerent directory of a repository is owned by someone else.
To fix it, make sure to set owner of extracted source files &
directories to the current user (root).
`git config --add safe.directory /path/to/fluentd-source` can also avoid
this issue but it's not appropriate on self build case.
=> Fix cannot build fluentd correctly on Ubuntu bionic & focal

td-agent/yum/td-agent.spec.in
build_id links may be useful for debug but there is a case that
build_id conflicts with other packages. (e.g. gitlab-ce)
Thus "_build_id_links compat" may not be suitable, so change it to
traditional alldebug.
Before: 
td-agent contains /usr/lib/debug/.build-id/xx/yy
After: 
td-agent-debuginfo contains /usr/lib/debug/.build-id/xx/yy
NOTE: rpm --excludepath may be a workaround to install, but it is not
so good.
Closes: #370
=> yum: generate build_id in -debuginfo

td-agent/Gemfile, td-agent/Gemfile.lock
Fixes #355.
Windows Exporter plugin is a system metrics plugin for Win32 platforms.
It can capture a wide range of metrics (CPU, memory, and network etc.),
and is very convenient for monitoring Windows nodes.
* https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter
* https://rubygems.org/gems/fluent-plugin-windows-exporter
The plugin enables Fluentd to act as a replacement of general system
monitoring solution (such as collectd or Prometheus), and should be
very useful for Windows administrators.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Add fluent-plugin-windows-exporter

.github/workflows/windows.yml, td-agent/msi/Dockerfile
3.5-windowsservercore-ltsc2022 lacks something to build td-agent.
Fix #382
=> msi: Use `3.5-windowsservercore-ltsc2019` explicitly to build container

td-agent/Rakefile, td-agent/config.rb
=> msi: Replace OpenSSL with MinGW's latest one to fix memory leak

td-agent/manage-fluent-repositories.sh
In the previous versions, it seems that prefix with vendor is not set.
Unexpectedly, the previous version set it. so apt update complains
mismatch of Origin and Label.
Before: InRelease
Origin: ubuntu/focal focal
Label: ubuntu/focal focal
After: InRelease
Origin: focal focal
Label: focal focal
This commit follows the previous behavior.
=> package: do not include extra prefix for publish snapshot

td-agent/Gemfile, td-agent/Gemfile.lock
async-2.0 requires Ruby 3.0 or later but we still support Ruby 2.7 until EOL.
=> Stay async-1.30 to avoid upgrading to 2.0

td-agent/Rakefile
Suppress following error of rpmlint:
```
td-agent.x86_64: E: non-standard-dir-perm /opt/td-agent/lib/ruby/gems/2.7.0/gems/cmetrics-0.2.5/ext/cmetrics/tmp/x86_64-redhat-linux/ports/cmetrics/0.2.2/cmetrics-0.2.2 775
A standard directory should have permission set to 0755. If you get this
message, it means that you have wrong directory permissions in some dirs
included in your package.
...
```
```
td-agent.x86_64: E: non-readable /opt/td-agent/lib/ruby/gems/3.1.0/gems/cmetrics-0.2.5/ports/archives/v0.2.2 600
The file can't be read by everybody. Review if this is expected.
```
=> Remove needless files in cmetrics gem

.github/workflows/yum-arm.yml, .github/workflows/yum.yml, td-agent/Rakefile, td-agent/convert-artifacts-layout.sh, td-agent/yum/almalinux-9-aarch64/from, td-agent/yum/almalinux-9/Dockerfile, td-agent/yum/almalinux-9/qemu-dummy-static, td-agent/yum/binstubs-test.sh, td-agent/yum/install-test.sh, td-agent/yum/pkgsize-test.sh, td-agent/yum/rpmlint.config, td-agent/yum/serverspec-test.sh, td-agent/yum/td-agent.spec.in
=> Try to add AlmaLinux 9

td-agent/manage-fluent-repositories.sh
* Remove needless S3 profile argument for `deb` and `rpm` commands
* Drop xenial support
* Add `dry-download` and `dry-upload` commands
* Automate copying generated files of apt repositories
=> Tweak manage-fluent-repositories.sh

td-agent/apt/debian-buster/Dockerfile, td-agent/apt/ubuntu-bionic/Dockerfile, td-agent/yum/rockylinux-8/Dockerfile
Recently `gem install bundler` installs Bundler v2.4 or later which requires Ruby 2.6 or later, but some of our Docker images still use Ruby 2.5. It causes build error like this:
https://github.com/fluent/fluent-package-builder/actions/runs/3908735547/jobs/6711234402
* For Rocky Linux 8 it can easily update Ruby to 3.1 by `dnf module enable ruby:3.1`
* For debian-buster it's [already EOL](https://wiki.debian.org/DebianReleases). So we no longer take care of it. Just stay bundler to v2.3.26.
* For ubunt-bionic [it's close to EOL](https://wiki.ubuntu.com/Releases). So we no longer take care of it too. Just stay bundler to v2.3.26.
FYI: Ruby 2.5 is used to run `rake` for build, it's not included in built packages.
=> Fix build error of Docker images due to using older Ruby

td-agent/Rakefile
File.exists? is removed as of Ruby 3.2
=> Replace File.exists? with File.exist?

td-agent/yum/amazonlinux-2023/Dockerfile, td-agent/yum/td-agent.spec.in
Even when ruby3.1 is specified, dnf downloads Ruby 3.2 in actual on Amaxon Linux 2023.
=> Amazon Linux 2023: Use Ruby 3.2 to build explicitly

.github/workflows/apt-arm.yml, .github/workflows/yum-arm.yml
They take too long time to complete on CI environment since they use QEMU. Due to this they often time out.
Instead trigger them manually by `workflow_dispatch`. 
In addition, I'm considering to prepare self-hosted runner for them.
=> CI: Don't trigger build actions for Arm platform automatically

td-agent/Rakefile
"debian/copyright" and "debian/source/include-binaries" are generated to "debian/copyright" not "#{PACKAGE_NAME}/debian/copyright" and so on. If we use wrong path to `file`, we always regenerate these files. It slows down `rake apt:build`.
=> td-agent-v4: deb: Remove needless "#{PACKAGE_NAME}" prefix (#442)

.github/workflows/apt-arm.yml, .github/workflows/yum-arm.yml
They take too long time to complete on CI environment since they use QEMU. Due to this they often time out.
Instead trigger them manually by `workflow_dispatch`.  In addition, I'm considering to prepare self-hosted runner for them.
=> td-agent-v4: CI: Don't trigger build actions for Arm platform automatically (#439)

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, td-agent/Rakefile
=> td-agent-v4: Drop Debian buster

fluent-package/apt/piuparts-test.sh
* xenial (16.04LTS) was already reached EOL.
* do not skip piuparts for jammy (22.04)
* use recent gnupg (old version is used for xenial, no
need to do so)
* remove unused bionic configuration
* fix key verification failure of keyring path
=> apt: remove deprecated piuparts stuff

fluent-package/Rakefile, fluent-package/apt/commonvar.sh, fluent-package/apt/debian-bookworm-arm64/from, fluent-package/apt/debian-bookworm/Dockerfile, fluent-package/apt/debian-bookworm/qemu-dummy-static, fluent-package/apt/pkgsize-test.sh, fluentd-apt-source/Rakefile, fluentd-apt-source/apt/debian-bookworm/Dockerfile
Debian 12 (bookworm) is scheduled to be released 6/10.
Note that bookworm container adopts deb822 format by default.
deb822 is similar to RFS 822.
/etc/apt/sources.list.d/debian.sources:
Types: deb
URIs: http://deb.debian.org/debian
Suites: bookworm bookworm-updates
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
=> deb: add bookworm

fluent-package/msi/localization-en-us.wxl
It seems that we need to fix this feature name too, related to 
* #449
=> msi: migrate FeatureMainName

fluent-package/yum/fluent-package.spec.in
prelink is introduced for performance gain, but in recent days, it seems in common to disable prelink by default. (CentOS 7 or later, it was disabled)
FYI:
https://pagure.io/fesco/issue/1183
https://support.oracle.com/knowledge/Oracle%20Linux%20and%20Virtualization/2658080_1.html
=> rpm: drop deprecated prelink configuration

fluent-package/templates/usr/sbin/fluentd.erb
To align with Linux service definition.
=> dmg: use compatible service name for config and socket

fluent-package/Rakefile, fluent-package/dmg/resources/pkg/Distribution.xml.erb
It should be fine as long as it is unique.
`org.fluent.fluentd` would be appropriate.
=> dmg: change identifier

fluent-package/Rakefile, fluent-package/templates/fluentd.plist.erb
Change both `/opt/fluent/usr/sbin/` and `/opt/fluent/usr/bin/` paths
to `/opt/fluent/sbin/` for simplicity.
Note: we can't put them into `/opt/fluent/bin/` because the filenames
conflict with internal Fluentd gems.
=> dmg: fix bin scripts paths

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
This fixes the not found path to upload in apt.
Warning: No files were found with the provided path:
td-agent/apt/repositories. No artifacts will be uploaded.
Warning: No files were found with the provided path:
td-agent-apt-source/apt/repositories. No artifacts will be uploaded.
=> CI: update package name to fluent-package

fluent-package/Rakefile, fluent-package/msi/assets/fluent-gem.bat, fluent-package/msi/assets/fluent-package-prompt.bat, fluent-package/msi/assets/fluentd.bat, fluent-package/msi/assets/td-agent-gem.bat, fluent-package/msi/exclude-files.xslt, fluent-package/msi/install-test.ps1, fluent-package/msi/serverspec-test.ps1, fluent-package/msi/source.wxs
msi: migrate td-agent*.bat
Before:
c:\opt\td-agent\bin\td-agent.bat
c:\opt\td-agent\bin\td-agent-gem.bat
After:
c:\opt\td-agent\fluentd.bat
c:\opt\td-agent\fluent-gem.bat
If td-agent-gem.bat was renamed to fluent-gem.bat, it conflict with
c:\opt\td-agent\fluent-gem.bat which fluentd gem provides.
Not to cause such a situation, put them under c:\opt\td-agent.
To keep compatibility, td-agent.bat and td-agent-gem are provided
as hardlink.
=> msi: migrate td-agent*.bat

fluent-package/Rakefile, fluent-package/msi/assets/fluent-package-post-install.bat, fluent-package/msi/assets/fluent-package-version.rb, fluent-package/msi/assets/fluentd.bat, fluent-package/msi/build.bat, fluent-package/msi/install-test.ps1, fluent-package/msi/serverspec-test.ps1, fluent-package/msi/source.wxs
Before:
c:\opt\td-agent\
After:
c:\opt\fluent\
Note that the following files are not migrated yet:
c:\opt\td-agent\etc\td-agent.conf
c:\opt\td-agent\etc\plugin
c:\opt\td-agent\td-agent.log
c:\opt\td-agent\var\log\td-agent
Thus, most of files are placed under c:\opt\fluent, but these
files are remained for keeping compatibility.
=> msi: migrate to /opt/fluent

fluent-package/msi/Dockerfile
wixtoolset: requrie .net 3.5
chocolatey: requrie .net 4.8
runtime:3.5 doesn't contain .net 4.8, and chocolatey try to install .net 4.8 during install process, as a result, it causes the following error:
```
Please reboot the system and try to install/upgrade Chocolatey again.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocoInstall\t ools\chocolateysetup.psm1:815 char:11
+           throw ".NET Framework 4.8 was installed, but a reboot is re ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (.NET Framework ...ocolatey ag
ain.:String) [], RuntimeException
+ FullyQualifiedErrorId : .NET Framework 4.8 was installed, but a reboot i
s required.
```
=> msi: use sdk: image for prerequisite

fluent-package/Rakefile, fluent-package/templates/etc/systemd/fluentd.service.erb, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm, fluent-package/templates/usr/lib/tmpfiles.d/fluentd.conf, fluent-package/yum/fluent-package.spec.in, serverspec/linux/td-agent.rb
for deb, according Debian policy, dynamically allocated name should be prefixed
with an underscore.
(It may be not applicable for group name, but there is an prefixed
group name example e.g. _ssh/_cvsadmin)
See
https://www.debian.org/doc/debian-policy/ch-opersys.html#introduction
Note that adduser doesn't accept _name prefix by default. To avoid
it, we need to specify --force-badname explicitly
* migration from to td-agent to _fluentd
* service, hook script, tmpfiles.d and so on.
* cleanup td-agent statoverride
For rpm, no prefixed underscore for user/group name.
* migration from td-agent to fluentd
* service, hook script, tmpfiles.d, permission and so on.
* cleanup user/group on removing package
=> migrate to new user/group name

.github/workflows/apt.yml, .gitignore, Vagrantfile, fluent-package/apt/install-with-systemd-test.sh
This adds a test for deb packages to confirm the package works correctly with systemd.
There are still some points that need more refactoring, but it is better to have such a test as soon as possible.
The current `Vagrantfile` is just for manual operation and is not used recently, so I fixed it entirely for CI.
=> deb: test with systemd

.github/workflows/yum.yml, Vagrantfile, fluent-package/yum/install-with-systemd-test.sh
The rpm version of #495
There is no `AmazonLinux2023` vagrant image, so I omit it for now.
=> rpm: test with systemd

fluent-package/Rakefile, fluent-package/apt/install-test.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/debian/fluent-package.install, fluent-package/dmg/resources/pkg/postinstall.erb, fluent-package/templates/etc/systemd/fluentd.erb, fluent-package/templates/etc/systemd/fluentd.service.erb, fluent-package/templates/fluentd.plist.erb, fluent-package/templates/opt/fluent/share/td-agent.conf.tmpl, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm, fluent-package/templates/usr/sbin/fluentd.erb, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/install-test.sh, fluent-package/yum/pkgsize-test.sh
In the previous versions, there are some configuration files and
log files are still kept under old path for compatibility.
It is better migrating to /opt/fluent completely, but we
need to consider upgrading from v4, too.
During upgrading from v4, seamless migration can be done by using
environment variable to specify the actual path because there is
no need to embed specific path to .service itself.
It aims not to be confused which configuration file should be applied.
Before:
* Use old path for compatibility.
* /etc/td-agent/td-agent.conf
* /etc/td-agent/plugin
* /var/log/td-agent/
After:
* Use /opt/fluent as possible.
* Keep /opt/td-agent as possible (only upgrading)
* Moving content under /etc/td-agent to /etc/fluent/
* Moving content under /var/log/td-agent to /var/log/fluent
* …
=> migrate configuration files

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version.sh
When manually testing with script, script will be interrupted with pager. This commit explicitly disable such feature.
=> apt: apply --no-pager to disable pager on tty

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/templates/etc/systemd/fluentd.service.erb
No need to use old path for fluent-package.
=> Use new path for fluent-package

fluent-package/apt/systemd-test/update-from-v4.sh
It is enough to check that the command fails.
=> deb: systemd test minor fix

fluent-package/apt/systemd-test/update-from-v4.sh
td-agent (alias of fluentd service) should be enabled, but systemctl status td-agent may fail frequently with exit 3. It means inactive (dead) status.
Until finding correct solution to fix this issue, disable it for a while.
=> test:  disable check with td-agent alias status

fluent-package/convert-artifacts-layout.sh, fluent-package/manage-fluent-repositories.sh
Both of distributions are already removed from GitHub Actions.
* buster: EOL (2022-09-10), though LTS is still alive (2024-06-30)
* bionic: End of Standard Support (June 2023), EOL April 2028
See
https://wiki.debian.org/DebianReleases
https://wiki.ubuntu.com/Releases
=> Update target distributions

fluent-package/Rakefile, fluent-package/apt/install-test.sh, fluent-package/templates/etc/logrotate.d/fluentd, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/install-test.sh
Before: /etc/logrotate.d/td-agent
If td-agent user/group exists, renaming td-agent
to fluent user/group then rewrite logrotate.d configuration.
But, it may fail if user modify that configuration unexpected
way.
After: /etc/logrotate.d/fluentd
If td-agent user/group exists (e.g upgrading from v4), create
_fluent user/group as same uid/gid. If not, just create new _fluent
user/group (no td-agent user/group).
This approach make easy to migrate /etc/logrotate.d/td-agent
configuration file without modification.
Additionally, rewrite /etc/logrotate.d/td-agent path of pid
because the pid file will be dynamically created/destroyed.
=> Migrate path of logrotate.d configration

fluent-package/apt/install-test.sh
This is follow-up #507. need to rebase it.
Ubuntu 22.04 was supported since 4.3.1-1, so
we can enable it.
=> deb: don't terminate test case for jammy

fluent-package/debian/control, fluentd-apt-source/debian/control
* Update description fluentd-apt-source
* Drop dependency to deprecated transitional apt-transport-https.
https support has been moved into the apt package.
=> deb: refine fluentd-apt-source 

fluent-package/msi/install-test.ps1, fluent-package/msi/serverspec-test.ps1, fluent-package/msi/source.wxs
Many users would be happier if it didn't start automatically:
* No one would be happy to start Fluentd with the default settings.
* It opens some ports by default. It is undesirable from a security point of view.
In addition, we should make sure that the service starts after all install actions are completed.
To achieve it, this is preferable for now.
=> msi: Disable auto start after install

fluent-package/Rakefile, fluent-package/msi/assets/fluent-package-post-install.bat, fluent-package/msi/assets/fluent-package-post-migration.bat, fluent-package/msi/assets/fluentd.bat, fluent-package/msi/exclude-files.xslt, fluent-package/msi/install-test.ps1, fluent-package/msi/source.wxs, fluent-package/templates/opt/fluent/share/td-agent.conf.tmpl
msi: migrate to c:\opt\fluent
Before:
* Configuration c:\opt\td-agent\etc\td-agent\td-agent.conf
* Log files: c:\opt\td-agent
After:
* Move configuration to c:\opt\fluent\etc\fluent\td-agent.conf
* Create symbolic link to c:\opt\fluent\etc\fluent from c:\opt\td-agent\etc\td-agent.
* Overwrite c:\opt\fluent\etc\fluentd.conf with td-agent.conf (when upgrade)
* Migrate to FLUENT_PACKAGE_TOPDIR environment variable.
* Keep old logs as is:
=> msi: migration to c:\opt\fluent

fluent-package/apt/systemd-test/update-from-v4.sh
Add `--now` to `systemctl enable` in update-from-v4.sh to make sure to start the service before checking the status.
=> apt: Fix an unstable systemd test

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/templates/package-scripts/fluent-package/deb/postinst
It fixes the following case:
Failed to restart fluentd.service: Unit fluentd.service not found.
dpkg: error processing package fluent-package (--configure):
installed fluent-package package post-installation script subprocess returned error exit status 5
=> deb: ensure to reload unit file before restarting

fluent-package/apt/systemd-test/update-from-v4.sh
We misunderstood the use of this option.
By default, `systemctl status` waits until the unit's start-up is completed (without `--no-block` option).
The option `--wait` is for blocking `systemctl start foobar` until the service `foobar` is stopped.
=> deb: Stop using `--wait` option of systemctl

fluent-package/Rakefile, fluent-package/apt/install-test.sh, fluent-package/templates/opt/fluent/share/td-agent-ruby.conf, fluent-package/yum/install-test.sh
It was used for prelink.
We don't use it since 66116d55088b4c055579d2ea3b326b48f0cc4d24.
=> Remove td-agent-ruby.conf

fluent-package/apt/install-test.sh, fluent-package/apt/serverspec-test.sh, fluent-package/debian/fluent-package.links, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/install-test.sh, fluent-package/yum/serverspec-test.sh
Before: create the following symbolic links
* /usr/sbin/td-agent
* /usr/sbin/td-agent-gem
After: create the following symbolic links only for upgrade
* /usr/sbin/td-agent
* /usr/sbin/td-agent-gem
=> create compatible symlink only for upgrade

fluent-package/Gemfile, fluent-package/Gemfile.lock
ref: https://www.ruby-lang.org/en/news/2023/06/29/redos-in-uri-CVE-2023-36617/
=> Update uri gem to suppress CVE-2023-36617

fluent-package/apt/install-test.sh, fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version.sh
* Fix inverted tests using `!`, which has always succeeded.
* Simplifies.
* Add some test cases.
=> deb: tweak tests

fluent-package/yum/install-test.sh, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
* Fix inverted tests using `!`, which has always succeeded.
* Simplifies.
* Add some test cases.
=> rpm: tweak tests

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-from-v4.sh
Without stopping before `unmask` and `enable`, sometimes Fluentd runs doubly.
=> deb: prevent Fluentd from running doubly

fluent-apt-source/debian/rules
Before:
fluentd-archive-keyring.gpg
fluentd.sources
After:
fluent-archive-keyring.gpg
fluent.sources
=> deb: use fluent- for keyring and .sources

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/test.sh, fluent-package/yum/systemd-test/update-from-v4-logrotation-config-edited.sh, fluent-package/yum/systemd-test/update-from-v4.sh
We need to support these cases.
* When the file is edited, RPM renames it to `td-agent.rpmsave`.
* When the file is not edited, RPM removes it.
=> rpm: fix logrotate config migration

fluent-package/yum/centos-7-aarch64/Dockerfile, fluent-package/yum/fluent-package.spec.in
Fix missing package issue on CentOS 7 aarch64.
#7 150.6 ---> Package xz-devel.aarch64 0:5.2.2-2.el7_9 will be installed
#7 150.8 --> Finished Dependency Resolution
#7 150.8 Error: Package: devtoolset-11-toolchain-11.1-2.el7.aarch64 (centos-sclo-rh)
#7 150.8            Requires: devtoolset-11-gcc-c++
#7 150.8 Error: Package: devtoolset-11-toolchain-11.1-2.el7.aarch64 (centos-sclo-rh)
#7 150.8            Requires: devtoolset-11-gcc
#7 150.8 Error: Package: devtoolset-11-toolchain-11.1-2.el7.aarch64 (centos-sclo-rh)
#7 150.8            Requires: devtoolset-11-gcc-gfortran
#7 150.8 Error: Package: devtoolset-11-toolchain-11.1-2.el7.aarch64 (centos-sclo-rh)
#7 150.8            Requires: devtoolset-11-gdb
#7 150.8  You could try using --skip-broken to work around the problem
#7 150.9  You could …
=> rpm: fix build failure on aarch64

fluent-package/manage-fluent-repositories.sh
It should match amazon/2023/aarch64 and amazon/2023/x86_64.
$ find td-agent-release/lts -regex "^td-agent-release/lts/5/\(redhat\|amazon\)/\([2789]\|2023\)/\(x86_64\|aarch64\)$"
td-agent-release/lts/5/amazon/2023/aarch64
td-agent-release/lts/5/amazon/2023/x86_64
td-agent-release/lts/5/amazon/2/aarch64
td-agent-release/lts/5/amazon/2/x86_64
td-agent-release/lts/5/redhat/8/aarch64
td-agent-release/lts/5/redhat/8/x86_64
td-agent-release/lts/5/redhat/7/aarch64
td-agent-release/lts/5/redhat/9/aarch64
td-agent-release/lts/5/redhat/9/x86_64
=> rpm: changed to match Amazon 2023

fluent-package/manage-fluent-repositories.sh
If you didn't import public key yet, verifying
with rpm -K fails (digests SIGNATURES NOT OK)
It help step how to fix missing import key.
=> rpm: ensure whether old key has been imported

fluent-package/yum/fluent-package.spec.in
Before:
v4 => v5 => upgrading... it will remove cpmpatible symlinks => v5.x
After:
v4 => v5 => upgrading... do not remove compatible symlinks => v5.x
=> rpm: do not always remove compatible symlink during upgrading

fluent-package/templates/package-scripts/fluent-package/deb/postrm
Before:
v4 => v5 => upgrading... it will remove cpmpatible symlinks => v5.x
After:
v4 => v5 => upgrading... do not remove compatible symlinks => v5.x
=> deb: drop compatible symlink when no upgrade mode

fluent-package/yum/systemd-test/install-newly.sh
for v5 test case, it should be /5/.
=> rpm: fix typo in baseurl

fluent-package/yum/serverspec-test.sh
Before:
* confluent 6.x series are already reaches EOL.
See https://docs.confluent.io/platform/current/installation/versions-interoperability.html
After:
* Switch to confluent 7.4, it will be supported until May 3, 2025.
* Use newer jdk for testing to avoid issue which is derived exception from
obsolete one.
* Use newer command line option for kafka-topics. (--zookeeper option
is deprecated)
=> rpm: update kafka related test case

CHANGELOG.md
We decided to treat v5.0.0 RC version, not GA.
So we should notice it to uers here.
=> CHANGELOG.md: Add notice about v5.0.0

fluent-package/yum/serverspec-test.sh, fluent-package/yum/systemd-test/install-newly.sh
Note that confluent-community-2.13 seems signed by deprecated SHA-1.
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9
=> rpm: enable AlmaLinux 9 test case

CHANGELOG.md
OpenSSL 3.1.0 for Windows: https://github.com/oneclick/rubyinstaller2/blob/1037499985fcaff2c471e88ed254a7b698e508f6/CHANGELOG-3.2.md?plain=1#L5
=> CHANGELOG: fix OpenSSL version for v5.0.0

fluent-package/templates/package-scripts/fluent-package/deb/postrm
Before:
* Missing removing /var/run
* /var/run/td-agent is kept when upgraded from v4.
After:
* group procedure to function
* purge /var/run during removing package
=> deb: refactor postrm script

fluent-apt-source/debian/copyright, fluent-lts-apt-source/debian/copyright, fluent-package/templates/package-scripts/fluent-package/deb/copyright
Upstream accepts URIs.
See https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#upstream-contact-field
=> deb: set correct contact

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, Vagrantfile, fluent-package/apt/install-test.sh, fluent-package/apt/piuparts-test.sh, fluent-package/apt/pkgsize-test.sh, fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/test.sh, fluent-package/apt/systemd-test/update-from-v4.sh
* github: drop redundant --mirror option
Use pre-configured chroot apt-line, so --mirror is redundant.
Without it, it causes the following error on bookworm:
The following packages have unmet dependencies:
fluent-package : Depends: libncurses6 (>= 6) but it is not installable
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list.d
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list.d/t
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list
github: add more .service check after removing
After removing fluent-package, the status of service files seems …
=> github: add missing bookworm as target

fluent-package/msi/assets/fluent-gem.bat, fluent-package/msi/assets/fluentd.bat, fluent-package/msi/source.wxs
When installing fluent-package to c:\Program Files, the space
character must be escaped correctly.
* sources.wxs
* For xml, double quote (") must be &quot;
* to escape double quote in literal, you must escape with ^&quote;
it is treated as ^", so it is properly quoted to execute:
"cmd" /c "fsutil ... "c:\Program Files .." "c:\Program Files...""
* fluentd.bat,fluent-gem.bat
* set FOO="..." assign extra double quote, it's troublesome because
extra double quote will be included when concatenating path.
The only way to avoid this problem is set "FOO=..." to assign it.
you can assign to FOO without extra double quote.
* to get RUBY_VERSION, use "usebackq" and execute command with
escaped command literal explicitly.
passed `^""C:\..." ....^"` literal are evaluated ^""C:\..."^".
=> msi: support path which contains space or parenthesis

fluent-package/templates/etc/logrotate.d/fluentd
Fix system user/group name in logrotate config
I had installed  `fluent-package` - `5.0.1-1` on ubuntu 22.04
```
ii  fluent-package 5.0.1-1      amd64        All in one package of Fluentd
```
With fluent-package v5 user/group name is changed to `_fluentd`
- https://github.com/fluent/fluent-package-builder/blob/v5.0.1/fluent-package/templates/package-scripts/fluent-package/deb/postinst#L13
- https://github.com/fluent/fluent-package-builder/blob/v5.0.1/fluent-package/templates/package-scripts/fluent-package/deb/postinst#L19
However user/group name in logrotate config is `fluentd`, which causes following failure
```
$ logrotate -f /etc/logrotate.d/fluentd
error: /etc/logrotate.d/fluentd:7 unknown user 'fluentd'
error: found error in /var/log/fluent/fluentd.log , skipping
```
I guess this …
=> Fix system user/group name in logrotate config

fluent-package/Rakefile, fluent-package/templates/etc/logrotate.d/fluentd
This is follow-up of #592 to fix problem correctly.
fluent-package/tempaltes/etc/logrotate.d/fluentd is used
for deb and rpm, so it should support both of different
system user/group respectively.
=> Fix system user/group name in logrotate.d/fluentd again

fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/yum/fluent-package.spec.in
When upgrading from v4, there is a possibility that fluentd user is not  created as system user.
Before:
Without --system, /var/lib/fluent will be created
After:
With --system, /var/lib/fluent will NOT be created
NOTE: Not to overlook it, use long option explicitly.
UID itself is kept in range of system user (td-agent), so not accessed via normal user.
=> rpm deb: add user as system user

fluent-package/manage-fluent-repositories.sh
Closes: #585
Specify the PR number like this. (Only the number or the full URL is valid too)
$ ./manage-fluent-repositories.sh download-artifacts pull/587
NOTE: You must set GITHUB_ACCESS_TOKEN in advance. See Fine-grained personal access tokens via
https://github.com/settings/tokens?type=beta
=> package: add command to download artifacts from GitHub

fluent-package/yum/fluent-package.spec.in, fluent-package/yum/install-test.sh, fluent-package/yum/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
In the previous versions (5.0.0, 5.0.1), when fluent-package was
removed, system account (user and group are intended to be removed)
But there is a case that it fails to remove fluentd group because of
compatible GID is assigned for td-agent and fluentd when
fluent-package was introduced with upgrading from td-agent v4.
Removing fluentd user...
userdel: group fluentd is the primary group of another user and is not removed.
Removing fluentd group...
groupdel: cannot remove the primary group of user 'td-agent'
Removing td-agent user...
userdel: td-agent mail spool (/var/spool/mail/td-agent) not found
userdel: td-agent home directory (/var/lib/td-agent) not found
This is a bug of fluent-package apparently.
This kind of inconsistency causes maintainer script error when
reinstalling td-agent …
=>  rpm: do not delete system account

fluent-package/apt/systemd-test/downgrade-to-v4.sh, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/downgrade-to-v4.sh, fluent-package/yum/systemd-test/test.sh
github: check downgrade to v4
To downgrade correctly you must:
* Remove fluent-package in beforehand.
* Manually migrate buffer or logs
* Re-install td-agent v4.
NOTE: on debian/ubuntu, need to disable td-agent.service alias
beforehand because:
* It conflict with v4 td-agent.service
* If you didn't disable it, it causes broken symlink from td-agent.service to /lib/systemd/system/fluentd.service.
=> github: check downgrade to v4

fluent-package/msi/assets/fluent-package-prompt.bat
* fix https://github.com/fluent/fluent-package-builder/issues/605
* The current PATH includes `"`. It is unintended and causes some
bugs. For example, fluent-diagtool does not work correctly
because of this.
=> msi: fix wrong env path for Fluent Package Prompt

fluent-package/msi/assets/fluent-package-prompt.bat
The last character of `%~dp0` is `\`, so we don't need add it.
(Though it appears it does not cause any problems.)
=> msi: remove unnecessary path delimiter

fluent-package/apt/ubuntu-focal/Dockerfile, fluent-package/yum/amazonlinux-2/Dockerfile, fluent-package/yum/centos-7/Dockerfile
There are some distribution which can't support the latest version of bundler because the version of ruby is 2.6.
=> ci: use the last supported version on each distribution to fix failure

fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
In the previous versions, the enabled service status of td-agent was not migrated.
This commit try to take over existing td-agent service status.
Note that if systemctl enable fluentd is executed in %post section, it was reverted in td-agent's %preun scriptlet.
So it is enabled in %posttrans explicitly.
Closes: #610
=> rpm: take over enabled state of systemd service from v4

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
There was a case that missing quote about file name causes migration failures.
* No quote under /etc/td-agent/'PATH_WITH_SPACE'
* No quote under /var/log/td-agent/'PATH_WITH_SPACE'
Usually such files should not be generated, but need to care it in practical use case.
=> deb rpm: quote target files

fluent-package/apt/commonvar.sh, fluent-package/msi/update-from-v4-test.ps1
The last version of td-agent v4 is 4.5.2.
=> ci: use last end of version for CI

fluent-package/Rakefile, fluent-package/config.rb, fluent-package/patches/rubyinstaller/0001-Avoid-crash-on-invalid-registry-key-while-detecting-.patch
When a non-ASCII key exists under the registry key `SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall/`, Fluentd fails to start workers due to `Encoding::UndefinedConversionError`. This patch avoid this issue.
Fix #616
=> Add a patch for RubyInstaller to avoid crash on start up

.github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/yum.yml
actions/download-artifact@master branch is already deprecated and switched to main branch. 
(master branch is 121 commits behind main)
There is no need to always dare to follow main branch, so use stable v4 release.
=> github: use stable actions/download-artifact@v4

CHANGELOG.md, td-agent/Rakefile, td-agent/config.rb, td-agent/debian/changelog, td-agent/patches/rubyinstaller/0001-Avoid-crash-on-invalid-registry-key-while-detecting-.patch, td-agent/yum/td-agent.spec.in
When a non-ASCII key exists under the registry key `SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall/`, Fluentd fails to start workers due to `Encoding::UndefinedConversionError`. This patch avoid this issue.
Backported from v5.0.3: #620
=> td-agent-v4: Backport #620

fluent-package/Gemfile, fluent-package/Gemfile.lock, fluent-package/Rakefile, serverspec/windows/td-agent.rb
Until https://github.com/chef/win32-service/pull/85 is merged,
use forked version of win32-service.
This fix should be applied to fluent-package not to block starting
fluentdwinsvc service on Windows.
See https://github.com/fluent/fluent-package-builder/issues/618
Closes: #630
NOTE: even though just putting the following line
does not install forked version of win32-service, so
install it explicitly as same as fluentd gem.
```
gem "win32-service", github: "fluent-plugins-nursery/win32-service",
branch: "fluent-package", platforms: [:mingw, :x64_mingw]
```
=> msi: fix slow start issue on Windows

.github/workflows/apt.yml, Rakefile
In the previous versions, fluent-lts-apt-source package was built manually and integrated into repository.
Now it will be built with apt:build rake task.
=> deb: enable building fluent-lts-apt-source package

fluent-package/convert-artifacts-layout.sh
In the previous versions, there is a case that
fluent-apt-source and fluentd-apt-source packages were moved under f/fluent-lts-apt-source
This PR fixes to add restriction rule for lts package name.
=> apt: changed to match fluent-lts-apt-source correctly

fluent-package/convert-artifacts-layout.sh
In the previous versions, 'fluent*-apt-source*.deb' matches not only fluent-apt-source and fluentd-apt-source, but also matches fluent-lts-apt-source.
fluent-lts-apt-source should not put under contrib/f/fluent-apt-source because aptly raises exception when fluent-lts-apt-source is placed under contrib/f/fluent-apt-source/.
=> apt: do not copy fluent-lts-apt-source under fluent-apt-source/

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/test.sh
Before:
test.sh execute multiple test files.
This behavior make it hard to distinct failure test cases.
After:
Use test.sh as launch script. It doesn't execute multiple test files.
This change was introduced to make it easy to distinct each test
cases on error.
=> github: extract test file as element of matrix

fluent-package/msi/install-test.ps1
Add a test for
* #618
On v5.0.2, I have confirmed it takes 4.6s ~ 6.7s.
https://github.com/daipom/fluent-package-builder/actions/runs/8417853364/job/23047108305#step:7:168
On the master, it takes less than 1s.
https://github.com/daipom/fluent-package-builder/actions/runs/8417835331/job/23047050065#step:7:167
=> CI: Check time to start service on Windows

fluent-package/test-install-in-docker.sh, fluent-package/test-verify-repo.sh
Use case:
* upload pre-built packages on test/experimental before release
* check whether repository metadata is correctly updated
Currently added helper script will be executed on local machine.
If repository metadata is valid, it reports something like:
```
Complete!
Succeeded to install 5.0.3 on "amzn" from exp/lts/5
OK: debian:bullseye exp/5
OK: debian:bullseye exp/lts/5
OK: debian:bookworm exp/5
OK: debian:bookworm exp/lts/5
OK: ubuntu:focal exp/5
OK: ubuntu:focal exp/lts/5
OK: ubuntu:jammy exp/5
OK: ubuntu:jammy exp/lts/5
OK: centos:7 exp/5
OK: centos:7 exp/lts/5
OK: almalinux:8 exp/5
OK: almalinux:8 exp/lts/5
OK: rockylinux:9 exp/5
OK: rockylinux:9 exp/lts/5
OK: amazonlinux:2 exp/5
OK: amazonlinux:2 exp/lts/5
OK: amazonlinux:2023 exp/5
OK: amazonlinux:2023 exp/lts/5
```
=> ci: add helper script to test updated repository metadata

.github/workflows/apt.yml, Rakefile, fluent-package/apt/confluent-test.sh, fluent-package/apt/serverspec-test.sh, serverspec/kafka/confluent.rb, serverspec/linux/td-agent.rb
In the previous versions, testing with confluent is
executed in serverspec:linux.
As confluent test case should be out of scope about basic serverspec
to distinct confluent's failure, so extract them as isolated test case.
* github ci: added "Confluent Test"
* Upgrade confluent from 6.0 to 7.6
* Replace deprecated --zookeeper option to --bootstrap-server to
create kafka topics
=> ci deb: extract confluent test case

.github/workflows/yum.yml
Since the Linux Containers project has made the decision to phase out access to linuxcontainers.org image server for LXD users, so we need to switch to new image server to use cgroup v1 images.
See
* https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479
* https://discourse.ubuntu.com/t/new-lxd-image-server-available-images-lxd-canonical-com/43824
=> github: update remote image server

fluent-package/msi/assets/fluent-gem.bat, fluent-package/msi/assets/fluentd.bat
* Add entire local scope to prevent changing global env vars
* Remove unnecessary enabledelayedexpansion
* Remove unnecessary `/`
Before: `FLUENT_PACKAGE_VERSION`  was passed to Fluentd process.
After: `FLUENT_PACKAGE_VERSION` is not passed to Fluentd process.
Previously, it changed the environment variables unintentionally.
Before
```console
> ruby -e "ENV['PATH'].split(';').select{|v| v.include?('fluent')}.map{|v| p v}"
"C:\\opt\\fluent\\"
"C:\\opt\\fluent\\bin"
> fluent-gem --version
3.4.19
> ruby -e "ENV['PATH'].split(';').select{|v| v.include?('fluent')}.map{|v| p v}"
"C:\\opt\\fluent\\bin"
"C:\\opt\\fluent\\"
"C:\\opt\\fluent\\bin"
```
After
```console
> ruby -e "ENV['PATH'].split(';').select{|v| v.include?('fluent')}.map{|v| p v}"
"C:\\opt\\fluent\\"
"C:\\opt\\fluent\\bin"
> …
```
=> msi: refactor exectuion bat files

fluent-package/msi/assets/fluentd.bat, fluent-package/msi/install-test.ps1
* Partially (msi) solves #611
* Inspired by #622
* This is another version that does not add a new option and considers some options to skip checking duplicate launches.
* Both #622 and this can be a solution to #611
* Let's consider how to solve it based on the information so far.
Before:
We can launch Fluentd by fluentd.bat even though fluentdwinsvc is running.
Launching multiple Fluentd with the same config may cause inconsistency of the buffers or the pos files.
After:
We can't launch Fluentd by fluent.bat with the default config path if fluentdwinsvc is running.
If one of the following options is specified, we can execute fluentd.bat as before.
* `--config` (`-c`)
* `--dry-run`
* `--reg-winsvc`
* `--reg-winsvc-fluentdopt`
When the `fluentdwinsvc` is running, the behavior of …
=> msi: guard duplicated instance (not adding a new option)

.github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum.yml
There is no need to waste CI resources.
ref.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> github: restrict execution timeout

fluent-package/apt/systemd-test/install-newly.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/templates/usr/sbin/fluentd.erb, fluent-package/yum/systemd-test/install-newly.sh, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
linux: guard duplicated instance (not adding a new option)
Closes: #611 
Before:
We can launch Fluentd by /usr/sbin/fluentd even though fluentd service
is running.
Launching multiple Fluentd with the same config may cause
inconsistency of the buffers or the pos files.
After:
We can't launch Fluentd by /usr/sbin/fluentd with the default config
path if fluentd service is running.  If one of the following options is
specified, we can execute fluentd as before.
* --config (-c)
* --dry-run
```
$ sudo /usr/sbin/fluentd 
Error: Can't start duplicate Fluentd instance with the default config.
To start Fluentd, please do one of the following:
(Caution: Please be careful not to start multiple instances with the same config.)
- Stop the Fluentd service 'fluentd'.
- Specify the config path explicitly …
```
=> linux: guard launching duplicated fluentd instance with same configuration

.github/workflows/yum-arm.yml, .github/workflows/yum.yml
CentOS 7 has reached EOL, so drop support for building it.
NOTE: keep build recipe for a while
=> github: drop CentOS 7 from GitHub workflow

fluent-package/convert-artifacts-layout.sh
CentOS:7 amd64 binary can be built but not for arm64 anymore. It seems that arm64 specific hotfix is required.
(but such a effort is not maintainable anymore because of EOL)
=> rpm: drop centos:7 to collect artifacts

fluent-package/msi/assets/fluentd.bat, fluent-package/templates/usr/sbin/fluentd.erb
In the previous versions, guard duplicated instance mechanism was introduced.
But it should not block -h/--help and so on because user may refer command line option in such a case.
=> Fix a bug that excessively block to launch

fluent-package/test-install-in-docker.sh
* set noninteractive not to block
* do not set UID explicitly on ubuntu
* switch to baseurl (only for testing with local container)
=> Improve test script

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/Rakefile, fluent-package/apt/binstubs-test.sh, fluent-package/apt/confluent-test.sh, fluent-package/apt/install-test.sh, fluent-package/apt/piuparts-test.sh, fluent-package/apt/pkgsize-test.sh, fluent-package/apt/serverspec-test.sh, fluent-package/binstubs-test.rb, fluent-package/debian/rules, fluent-package/yum/binstubs-test.sh, fluent-package/yum/pkgsize-test.sh, fluent-package/yum/serverspec-test.sh, lib/package-task.rb
To investigate build log effectively, grouping log is better to do.
=> deb rpm: group logging

.github/workflows/yum.yml, fluent-package/apt/confluent-test.sh, fluent-package/run-confluent.sh, fluent-package/yum/binstubs-test.sh, fluent-package/yum/confluent-test.sh, fluent-package/yum/install-test.sh, fluent-package/yum/serverspec-test.sh, fluent-package/yum/systemd-test/commonvar.sh, serverspec/kafka/confluent.rb, serverspec/linux/td-agent.rb, serverspec/spec_helper.rb
test packaged rdkafka usability.
* Refactor confluent test case (Unify some script)
* Changed to execute confluent test with AlmaLinux, Amazon Linux and so on
* Drop limitation not to execute on Amazon Linux 2/2023
=> rpm: add confluent (kafka) test case

fluent-package/manage-fluent-repositories.sh
Switch signing key when fluent-apt-source package
was installed to most of machines.
As we can't measure such a metrics, just switch after a while. 
(It is important to determine "WHEN" we should switch to.
Before:
Treasure Data, Inc (Treasure Agent Official Signing key)
After:
Fluentd developers (Fluent Package Official Signing Key)
Closes: #579
=> deb: switch package signing key

fluent-package/manage-fluent-repositories.sh
By PR#580, signing key was changed by default, but it doesn't follow for rpm package signing yet.
=> rpm: unify to signing key

fluent-package/apt/piuparts-test.sh
Since v5.1.0, signing key was changed, so it should be included in archive key for piuparts.
=> apt: fix broken piuparts test case

README.md
As we won't update centos:7 package and supported ubuntu 24.04 recently.
=> Update supported platform example in README.md

.github/workflows/yum.yml
It appears that now the default `remote images` is https://images.lxd.canonical.com.
I don't know why, but we can't remove `images`.
The following command does nothing, so this step fails.
lxc remote remove images
=> ci: fix failing Test (CGroup V1)

fluent-package/Rakefile
Seems It appears to be taking a long time to install ruby gems on windows environment. So this patch will introduce parallel install to reduce installation time.
=> Rakefile: install ruby gems with parallel

fluent-package/make-index-html.erb, fluent-package/make-index-html.rb
Currently, we use https://packages.treasuredata.com hosted on AWS
which is powered by Treasure Data Inc.
Recently, we coordinated with CNCF which provides access to Cloudflare
R2 resource. As no S3Browser functionality, so need to replace it with
alternative index.html.
=> deb rpm: add helper script to generate index.html for hosting site

.github/workflows/apt.yml, .github/workflows/yum.yml
Currently, it is bit hard to distinct each Test jobs
on fluent-package-builder/actions/runs page.
This is because Test (CGroup V1) matrix.label matrix.test-file
is shown by default.
This commit try to make it more visibility on that page.
=> github: try to use more customized test labels

fluent-package/Rakefile
It fixes the following warning (Since Ruby 3.1):
Rakefile:168: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
Rakefile:168: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
This does not change the content of fluent-package.
=> Fix deprecated usage of ERB.new

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/Rakefile, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/templates/etc/systemd/fluentd.service.erb, fluent-package/yum/systemd-test/update-to-next-version.sh
Embed fluent package info into environment variable
It is aimed to detect current running process's fluentd version and
so on from /proc/id/environ.
This fix introduce the following environment variables which contains
similar information as same as /usr/sbin/fluentd -v
* FLUENT_PACKAGE_VERSION
* FLUENT_PACKAGE_FLUENTD_VERSION
* FLUENT_PACKAGE_FLUENTD_REVISION
=> Embed fluent package info into environment variable

fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm
When upgrading package, the following hook is executed:
plugins should be installed before restarting service.
Before:
* old prerm
* new preinst collect plugin information
* old postrm auto restart
* new postinst install plugins
After:
* old prerm collect plugin information
* new preinst
* old postrm
* new postinst install plugins and auto restart
=> deb: fix install plugin hook order correctly

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/test.sh, fluent-package/apt/systemd-test/update-to-next-version-service-status.sh, fluent-package/yum/systemd-test/test.sh, fluent-package/yum/systemd-test/update-to-next-version-service-status.sh
There is specification difference between DEB and RPM.
At least, there should be tests to clarify the current specification.
The current specification:
* DEB
* The service is **enabled** by default.
* The service **starts automatically after new install**.
* The service starts automatically **when it was active OR enabled before update**.
* RPM
* The service is **disabled** by default.
* The service **does not start automatically after new install**.
* The service starts automatically **only when it was active before update**.
=> ci: add update tests about service status

fluent-package/apt/systemd-test/update-to-next-version-service-status.sh, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/debian/rules, fluent-package/yum/systemd-test/update-to-next-version-service-status.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
This PR integrates tests into into feature branches.
The changes are prepared at https://github.com/fluent/fluent-package-builder/pull/683
* Add --no-restart-after-upgrade option for dh_installsystemd in order to suppress restarting on ubuntu focal
* Fix tests for no-downtime feature to confirm no-restart at upgrading package
* Note: Debian/Ubuntu packages need to fix migration_from_v4_main_process and restart at upgrade time. This causes some tests to fail on Debian/Ubuntu.
=> Add tests and fixes to no-downtime feature branch

.github/workflows/yum.yml
lxc launch will fail (/var/snap/lxd/common/lxd/unix.socket: connect: permission denied) in some cases, but not sure why yet.
To investigate further more, try to collect snap information when workflow was failed.
=> rpm ci: collect diagnostic message for cgroup v1

.github/workflows/apt.yml, .github/workflows/yum.yml
To verify major upgrade in workflow, it needs
more package build time.
=> ci: extend timeout for v6 workflow

fluent-package/Gemfile, fluent-package/Gemfile.lock, fluent-package/Rakefile, fluent-package/config.rb
Use this to test this feature.
* https://github.com/fluent/fluentd/pull/4624
=> use Fluentd for the feature

.github/workflows/apt.yml
The package for Noble has already been released, so we should enable the tests.
=> ci: Noble: enable install-newly test

fluent-package/apt/systemd-test/downgrade-to-v4.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
Usually, transitional package (td-agent) will be installed when upgrading from v4. so it should be installed at the same time　
to test in practical use case.
=> ci: install transitional package

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/update-to-next-major-version.sh, fluent-package/bump-version-v6.patch, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/preinst, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/update-to-next-major-version.sh
Before:
* missing fluent-plugin was installed
After:
* missing fluent-plugin was installed
* missing dependency gem was also installed
NOTE:
* if missing gem requires development packages to build it, it will
fail.
* fluent-diagtool depends on highly systemd service, so it is simple
just to use fluent-gem detecting missing gems.
=> deb rpm: fix local dependency gem

fluent-package/templates/etc/systemd/fluentd.service.erb
Remove environment variables that prevent the Update/Reload without downtime feature. This is because an upgrade with a Ruby version update will not work correctly due to environment variables for the old Ruby.
=> Remove unnecessary GEM_HOME/GEM_PATH settings

fluent-package/apt/piuparts-test.sh
Since v5.1.0, signing key was changed, so it should be included in archive key for piuparts.
In LTS branch, even though old signing key is still used, but it might better to migrate.
ref. https://github.com/fluent/fluent-package-builder/pull/671
=> Backport: apt: fix broken piuparts test case (LTS)

fluent-package/Rakefile
Seems It appears to be taking a long time to install ruby gems on windows environment. So this patch will introduce parallel install to reduce installation time.
See https://github.com/fluent/fluent-package-builder/pull/674
=> Backport: Rakefile: install ruby gems with parallel (LTS)

.github/workflows/apt.yml, .github/workflows/yum.yml
Currently, it is bit hard to distinct each Test jobs on fluent-package-builder/actions/runs page.
This is because Test (CGroup V1) matrix.label matrix.test-file is shown by default.
This commit try to make it more visibility on that page.
ref. https://github.com/fluent/fluent-package-builder/pull/684
=> Backport: github: try to use more customized labels (LTS)

.github/workflows/yum.yml
It appears that now the default `remote images` is https://images.lxd.canonical.com.
I don't know why, but we can't remove `images`.
The following command do nothing, so this step fails.
lxc remote remove images
ref. https://github.com/fluent/fluent-package-builder/pull/675
=> Backport: ci: fix failing Test (CGroup V1) (LTS)

.github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .github/workflows/yum.yml
At first, assumed 3 branchs master, v5, lts-v5, but it might be enough for master (v5.x) and lts-v5 for a while.
=> github: fix target branch name

fluent-package/templates/package-scripts/fluent-package/deb/preinst, fluent-package/yum/fluent-package.spec.in
If user defined the custom GEM_HOME / GEM_PATH environment variables,
there is an error in gem migration when upgrading a package.
```
$ apt install ./fluent-package_5.1.0-1_amd64.deb
---(snip)---
$ apt install ./fluent-package_6.0.0-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'fluent-package' instead of './fluent-package_6.0.0-1_amd64.deb'
The following packages will be upgraded:
fluent-package
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/17.6 MB of archives.
After this operation, 2336 kB of additional disk space will be used.
Get:1 /root/fluent-package_6.0.0-1_amd64.deb fluent-package amd64 6.0.0-1 [17.6 MB]
(Reading database ... 46220 files and directories currently …
```
=> deb yum: use /usr/sbin/fluent-gem to migrate gems when upgrade

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/test.sh
rpm ci: collect diagnostic message for cgroup v1
lxc launch will fail (/var/snap/lxd/common/lxd/unix.socket: connect:
permission denied) in some cases, but not sure why yet.
To investigate further more, try to collect snap information when
workflow was failed.
ref. https://github.com/fluent/fluent-package-builder/pull/696
=> Backport: rpm ci: collect diagnostic message for cgroup v1 (LTS)

.github/workflows/windows.yml
Even though GitHub Actions' cache over limitations easily, it might better to cache only Windows.
=> Backport: ci msi: cache package to reduce build time

fluent-package/Rakefile
This PR will fix build error as following when build windows package:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/os-release
C:/fluent-package-5.1.0/fluent-package/Rakefile:1190:in `readlines'
C:/fluent-package-5.1.0/fluent-package/Rakefile:1190:in `render_fluent_package_c
onfig'
C:/fluent-package-5.1.0/fluent-package/Rakefile:547:in `block (2 levels) in defi
ne'
Tasks: TOP => msi:selfbuild => build:msi_config => build:rpm_fluent_package_conf
ig
(See full trace by running task with --trace)
rake aborted!
```
https://github.com/fluent/fluent-package-builder/actions/runs/11734401644/job/32690358756?pr=722#step:5:2539
=> Rakefile: fix build error of windows package

fluent-package/msi/assets/fluentd.bat
If users set custom GEM_HOME / GEM_PATH environment variables, the batch file will not work as expected.
Therefore, this patch will set the appropriate values in the batch file.
=> msi: set GEM_HOME / GEM_PATH in batch file

fluent-package/msi/assets/fluentd.bat
If users set custom GEM_HOME / GEM_PATH environment variables, the batch file will not work as expected. Therefore, this patch will set the appropriate values in the batch file.
=> Backport:  msi: set GEM_HOME / GEM_PATH in batch file

fluent-package/Gemfile.lock
This should fix following error when build Windows package on `feature-nodowntime` branch.
```
Downloading fluentd-1.17.1 revealed dependencies not in the API or the lockfile 
(logger (~> 1.6)).
Either installing with `--full-index` or running `bundle update fluentd` should 
fix the problem.
rake aborted! 
Command failed with status (34): [C:/opt/fluent/bin/bundle _2.3.27_ install ...]
C:/fluent-package-5.1.0/fluent-package/Rakefile:462:in `block (2 levels) in defi
ne'
Tasks: TOP => msi:selfbuild => build:all => build:licenses => build:gems => buil
d:ruby_gems
(See full trace by running task with --trace)
rake aborted!
```
=> Gemfile.lock: fix dependency due to fix build error on windows

fluent-package/apt/systemd-test/downgrade-to-v4.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
Usually, transitional package (td-agent) will be installed when upgrading from v4. so it should be installed at the same time　 to test in practical use case.
ref. https://github.com/fluent/fluent-package-builder/pull/709
https://github.com/fluent/fluent-package-builder/pull/711
=> Backport: ci: install transitional package

fluent-package/apt/systemd-test/downgrade-to-v4.sh
Now, no need to unmask td-agent because transitional td-agent package was installed before.
As unmask fluentd is not enough to cleanup td-agent inactive(dead) link so explicitly disable it to purge them.
=> ci deb: tweak downgrade test case

fluent-package/apt/systemd-test/downgrade-to-v4.sh
After removing fluent-package and td-agent,
fluentd.service file is linked to nonexistent file (masked), but td-agent service is still active unexpectedly, so explicitly stop that service.
=> Backport ci deb: tweak downgrade test case

.github/workflows/yum.yml
Before lxc launch container image, it might better to wait some extent for stabilizing CI as known tips.
It works well if you collect diagnostic message for it.
NOTE: this fix was already landed in feature-nodowntime branch.
=> ci yum: tweak cgroup v1 failure

fluent-package/test-install-in-docker.sh, fluent-package/test-verify-repo.sh
* show targets on startup
* show ID (e.g. debian:bookworm) when failed to compare versions
* skip test when "dummy" was specified for DEB_TARGETS/RPM_TARGETS
* logging for each test case (e.g. install-debian-bookworm-on-exp-lts-5.log)
=> package: improve verify helper

fluent-package/test-install-in-docker.sh, fluent-package/test-verify-repo.sh
* show targets on startup
* show ID (e.g. debian:bookworm) when failed to compare versions
* skip test when "dummy" was specified for DEB_TARGETS/RPM_TARGETS
* logging for each test case
=> Backport: package: improve verify helper

fluent-package/Gemfile.lock, fluent-package/config.rb
Use https://github.com/fluent/fluentd/tree/restart-without-downtime-test-for-1.18 for test as version 1.18.
=> replace Fluentd for 1.18 test

fluent-package/apt/systemd-test/update-to-next-version-with-auto-and-manual.sh, fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/preinst, fluent-package/yum/systemd-test/update-to-next-version-with-auto-and-manual.sh
This PR will allow to switch auto/manual restart settings with DEB package even when Fluentd is running.
=> deb: use auto/manual feature when old package supports

fluent-package/Gemfile.lock, fluent-package/config.rb
Follow update of:
* https://github.com/fluent/fluentd/tree/restart-without-downtime-test-for-1.18
=> update Fluentd for 1.18 test

fluent-package/Rakefile, fluent-package/apt/systemd-test/update-to-next-version.sh, fluent-package/templates/etc/systemd/fluentd.service.erb, fluent-package/yum/systemd-test/update-to-next-version.sh
This reverts commit c13789b9961cc102549ffc502c30ae564ddc91a7.
We discussed FLUENT_PACKAGE_VERSION and other environemnment variables.
we decided to revert the variables because we are not used them and we have to continue to migrate them when the package will be upgraded using zero downtime restart feature.
=> Revert "Embed fluent package info into environment variable"

fluent-package/Gemfile, fluent-package/Gemfile.lock, fluent-package/config.rb
* Update Fluentd to v1.18.0 (https://github.com/fluent/fluentd/releases/tag/v1.18.0).
* Update ServerEngine to v2.4.0 (https://github.com/treasure-data/serverengine/commit/c93a592bb9642cdb8880fe9366bbee37e5b764cd).
* Update the lock file by `bundle update` on Windows.
Note: Normally, we update dependencies at the time of release, but this time, we should do it first since we will add a new feature #713 that depends on these new versions.
=> update Fluentd and ServerEngine and other dependencies

fluent-package/Rakefile, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-version-service-status.sh, fluent-package/debian/fluent-package.install, fluent-package/templates/etc/needrestart/conf.d/50-fluent-package.conf
Since Ubuntu 24.04, needrestart package kicks service restart out of package maintainer scripts.
Take back fluentd service under control for us,
it had better to suppress it.
NOTE: It seems that needrestart package is available from EPEL 8/9, but it is broken for a long time, so just ignore it.
Needrestart package missing dependency
https://bugzilla.redhat.com/show_bug.cgi?id=2154293
Note: Extracted changes from the following commits on `feature-nodowntime` branch.
* 91d28f206328770ad21ac1f58c6c42ea87bc64ab
* 65ed4e03808be48018be4455d8f94eb3ceb87690
* d7186ea346deb98d685e1ba866f337280eb270cd
=> deb: suppress service restart by needrestart

fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-from-v4.sh
This PR will add test to confirm that fluentd should be restarted with updating from v4
=> ci: add test to check the service status with updating from v4

fluent-package/Rakefile
Add missing `prerm` script to include it in debian package
=> deb: include prerm script in debian package

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/update-to-next-major-version.sh, fluent-package/templates/package-scripts/fluent-package/deb/preinst, fluent-package/yum/fluent-package.spec.in, fluent-package/yum/systemd-test/update-to-next-major-version.sh
This allows users to manually manage plugins by setting FLUENT_PACKAGE_SERVICE_RESTART to manual.
For example, there will be cases where a user wants to use a particular plugin version.
=> auto plugin install: disable unless auto

fluent-package/yum/fluent-package.spec.in
We don't need to suppress this macro because this macro handles preset, not restart.
I have confirmed that this macro of the package for RHEL 9 is expanded as follows.
```bash
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
/usr/lib/systemd/systemd-update-helper install-system-units fluentd.service || :
fi
```
=> rpm: revert suppressing systemd_post macro

fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
I forgot to remove unnecessary lines at https://github.com/fluent/fluent-package-builder/pull/744
=> system-test: clean up a code where it install v4 package

fluent-package/templates/package-scripts/fluent-package/deb/postinst, fluent-package/templates/package-scripts/fluent-package/deb/postrm, fluent-package/templates/package-scripts/fluent-package/deb/preinst, fluent-package/templates/package-scripts/fluent-package/deb/prerm
Points
* FROM-package just leaves tmp files if it supports the features.
* TO-package trigger the features if there are those tmp files.
* Thus, we don't need to check the version.
* Make installing plugin and restarting the same condition.
Before
1. from-prerm(upgrade): Do nothing.
2. to-preinst(upgrade): Collect plugin-list. Confirm version.
3. Install TO-package
4. from-postrm(upgrade): Do nothing.
5. Uninstall FROM-package
6. to-postinst(configure): Install plugin and restart if need.
After
1. from-prerm(upgrade):
* Check auto or not.
* Leave plugin-list and pid if need.
2. to-preinst(upgrade): Set tmp files for TO-package.
3. Install TO-package
4. from-postrm(upgrade): Clean tmp files of FROM-package.
5. Uninstall FROM-package
6. to-postinst(configure): Install plugin and restart if …
=> deb: improve process timing for safety and simplicity

fluent-package/manage-fluent-repositories.sh
In the previous versions, it download artifacts from GitHub in serial not parallel, so it takes huge amount of times.
In this version, it tries to download them in parallel, so it fixes above issue.
=> Enable parallel download artifacts

fluent-package/apt/commonvar.sh, fluent-package/apt/systemd-test/update-from-v4.sh, fluent-package/apt/systemd-test/update-to-next-major-version.sh, fluent-package/apt/systemd-test/update-to-next-version-service-status.sh
As v5.2.0 was released,  needrestart suppression should be also checked.
Additionally extract check logic as common helper function.
=> ci: check whether needrestart was suppressed for v5

fluent-apt-source/Rakefile, fluent-apt-source/debian/changelog, fluent-apt-source/debian/rules, fluent-lts-apt-source/Rakefile, fluent-lts-apt-source/debian/changelog, fluent-lts-apt-source/debian/rules
Since apt 2.9.16, it rejects the keybox format files. So we should use
the armored format instead.
ref. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1088656#35
> The only format which is GnuPG specific, are for example its internal
> keybox keyrings, which I don't think has ever been used as any kind
> of public interchange format.
In practical use case, Debian 13 (trixie) or Ubuntu 25.04 will be
affected. Without it, it causes verification error with apt-get update.
=> Use armored keyring for APT repository

fluent-package/yum/amazonlinux-2023/Dockerfile
* It appears that the recent Amazon Linux 2023 image stops providing `which`.
* We need `which` to build `librdkafka 1.9.0` or later.
* https://github.com/confluentinc/librdkafka/pull/4353
=> amazonlinux-2023: ensure to install `which` command

fluent-package/yum/amazonlinux-2023/Dockerfile
Backport #784 
* It appears that the recent Amazon Linux 2023 image stops providing `which`.
* We need `which` to build `librdkafka 1.9.0` or later.
* https://github.com/confluentinc/librdkafka/pull/4353
=> Backport: amazonlinux-2023: ensure to install `which` command (#784)

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml, fluent-package/apt/commonvar.sh, fluent-package/yum/install-test.sh, fluent-package/yum/serverspec-test.sh
Backport #787 for LTS branch.
In the previous versions, LTS package for arm was built on bare metal arm machine.
It might be better to build it with GitHub Actions to integrate them for LTS release process.
=> Backport github: enable arm CI with ubuntu-24.04-arm host (#787)

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/macos.yml, .github/workflows/stale-actions.yml, .github/workflows/windows.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
OT: It should be checkout@main to follow HEAD.
=> github: use stable version of GitHub actions

fluent-package/manage-fluent-repositories.sh
Latest createrepo-c breaks compatibility with createrepo. For example, it does not create metadata (repodata/*) which can be handled yum in AmazonLinux 2.
To keep compatibility for such a distribution, need to specify --compatibility explicitly.
See https://github.com/rpm-software-management/createrepo_c/issues/383
=> Backport rpm: keep compatibility with createrepo

fluent-package/manage-fluent-repositories.sh
Latest createrepo-c breaks compatibility with createrepo. For example, it does not create metadata (repodata/*) which can be handled yum in AmazonLinux 2.
To keep compatibility for such a distribution, need to specify --compatibility explicitly.
See https://github.com/rpm-software-management/createrepo_c/issues/383
=> rpm: keep compatibility with createrepo

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/test.sh
It seems that AmazonLinux:2 container image is not available anymore from https://images.lxd.canonical.com/.
AmazonLinux:2 is still available from
https://images.linuxcontainers.org,
but it can't be added without interactive operation for LXD.
It seems that it is easy to use Incus as a workaround.
=> ci: use Incus instead of LXD

.github/workflows/windows.yml
Upcoming Fluentd requires Ruby 3.2 or later.
It fixes the following error:
```
stderr: fluentd-1.18.0 requires ruby version >= 3.2, which is
incompatible with the current version, 3.1.7
```
=> ci: bump hostedtoolcache Ruby to 3.2

.github/workflows/yum.yml, Vagrantfile, fluent-package/yum/systemd-test/downgrade-to-v5-lts.sh, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-major-version.sh, fluent-package/yum/systemd-test/update-to-next-version-with-auto-and-manual.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-without-data-lost.sh
ci: switch CGroup v1 test on vagrant (VirtualBox)
In the previous versions, AmazonLinux:2 image
was lost from LXD, so switched from LXD to Incus.
In this time, Ubuntu 20.04 runner will be removed from
GitHub Actions, so need to give up using 20.04 runner
for upcoming EOL (2025/04/15).
Thus, there is no CGroup V1 host runner available on GitHub Actions.
As a result, it means that there is no straightforward way to test package
on CGroup v1 host. (such as AmazonLinux:2, AmazonLinux:2023)
Instead, use vagrant (VirtualBox) to test fluent-package.
It enables to run VM with CGroup v1 to keep CI alive.
=> ci: switch CGroup v1 test with VirtualBox

.github/workflows/apt.matrix.json, .github/workflows/apt.yml, .github/workflows/windows.yml, .github/workflows/yum.matrix.json, .github/workflows/yum.yml
In the previous versions, some test cases are contained in Build job.
It should be executed in a separated job by nature.
=> ci: split some binary package tests

.github/workflows/apt-arm.yml, .github/workflows/yum-arm.yml
Unexpectedly, cache key was same with amd64/x86_64 workflows. It should be fixed with adding -arm64/-aarch64 identifier.
Before:
* amd64/x86_64 and arm64/aarch64 packages were cached in same key
After: 
* amd64/x86_64 and arm64/aarch64 packages were cached separately 
* It reduces each cache size
=> ci: make cache key unique to reuse cache correctly

.github/workflows/apt-arm.yml, .github/workflows/apt.yml, .github/workflows/yum-arm.yml, .github/workflows/yum.yml
Before:
Always execute "Install dependencies" even though build step
could be skipped.
After:
Skip "Install dependencies" step if build step is omitted.
It will reduces workflow execution times.
=> ci: skip "Install dependencies" conditionally

.github/workflows/apt-arm.matrix.json, .github/workflows/apt-arm.yml, .github/workflows/yum-arm.matrix.json, .github/workflows/yum-arm.yml
follow-up #809
In this PR, I've found apt-arm executes duplicated binstubs test.
=> ci: make parallel jobs on arm

fluent-package/msi/Dockerfile
https://community.chocolatey.org/packages/msys2/20250221.0.0
https://community.chocolatey.org/packages/ruby/3.2.8.1
=> msi: update toolchains

fluent-package/msi/Dockerfile
Backport #804 
To build the cmetrics gem with CMake 4.0, `CMAKE_POLICY_VERSION_MINIMUM` should be set appropriately, like:
```
env:
CMAKE_POLICY_VERSION_MINIMUM: 3.5
```
Ref.
https://cmake.org/cmake/help/latest/variable/CMAKE_POLICY_VERSION_MINIMUM.html
We are using docker to create Windows packages, but it seems that the environment variables are not propagating properly there.
So, I did the downgrade the CMake version.
=> Backport: ci: fix build error on Windows (#804)

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/test.sh
Backport #803 
It seems that AmazonLinux:2 container image is not available anymore from https://images.lxd.canonical.com/.
AmazonLinux:2 is still available from
https://images.linuxcontainers.org,
but it can't be added without interactive operation for LXD.
It seems that it is easy to use Incus as a workaround.
=> Backport: ci: use Incus instead of LXD (#803)

.github/workflows/windows.yml
Backport #806 
Upcoming Fluentd requires Ruby 3.2 or later.
It fixes the following error:
```
stderr: fluentd-1.18.0 requires ruby version >= 3.2, which is
incompatible with the current version, 3.1.7
```
NOTE: Though v1.18 will not be shipped for v5 branch, it is better not to use EOL toolchain.
=> Backport ci: bump hostedtoolcache Ruby to 3.2 (#806)

fluent-package/apt/systemd-test/test.sh, fluent-package/yum/systemd-test/test.sh
It fixes "other_args: unbound variable" error.
It was merged unexpectedly because of conflicting with backport.
=> Backport: follow-up backport #803

fluent-package/msi/Dockerfile
* https://community.chocolatey.org/packages/msys2/20250221.0.0 
* https://community.chocolatey.org/packages/ruby/3.2.8.1
20230718 is too old, so it causes missing archives on mirror sites.
=> Backport: msi: update toolchains (#815)

.github/workflows/yum.yml, Vagrantfile, fluent-package/yum/systemd-test/update-from-v4.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh
Backport #807 
ci: switch CGroup v1 test on vagrant (VirtualBox)
In the previous versions, AmazonLinux:2 image
was lost from LXD, so switched from LXD to Incus.
In this time, Ubuntu 20.04 runner will be removed from GitHub Actions, so need to give up using 20.04 runner for upcoming EOL (2025/04/15).
Thus, there is no CGroup V1 host runner available on GitHub Actions. As a result, it means that there is no straightforward way to test package
on CGroup v1 host. (such as AmazonLinux:2, AmazonLinux:2023)
Instead, use vagrant (VirtualBox) to test fluent-package. It enables to run VM with CGroup v1 to keep CI alive.
=> Backport: ci: switch CGroup v1 test with VirtualBox (#807)

.github/workflows/apt.matrix.json, .github/workflows/apt.yml, .github/workflows/windows.yml, .github/workflows/yum.matrix.json, .github/workflows/yum.yml
Backport #809 
In the previous versions, some test cases are contained in Build job. It should be executed in a separate job by nature.
=> Backport: ci: split some binary package tests (#809)

.github/workflows/apt-arm.yml, .github/workflows/yum-arm.yml
Unexpectedly, cache key was same with amd64/x86_64 workflows. It should be fixed with adding -arm64/-aarch64 identifier.
Before:
* amd64/x86_64 and arm64/aarch64 packages were cached in same key After:
* amd64/x86_64 and arm64/aarch64 packages were cached separately
* It reduces each cache size
=> Backport ci: make cache key unique to reuse cache correctly (#811)

.github/workflows/apt-arm.matrix.json, .github/workflows/apt-arm.yml, .github/workflows/yum-arm.matrix.json, .github/workflows/yum-arm.yml
follow-up #809
In this PR, I've found apt-arm executes duplicated binstubs test.
=> Backport ci: make parallel jobs on arm (#813)

fluent-package/yum/systemd-test/setup-rpmrebuild.sh, fluent-package/yum/systemd-test/update-to-next-version-service-status.sh, fluent-package/yum/systemd-test/update-to-next-version-with-auto-and-manual.sh, fluent-package/yum/systemd-test/update-to-next-version-with-backward-compat-for-v4.sh, fluent-package/yum/systemd-test/update-to-next-version.sh
RpmUnpack implementation was changed from rpm2cpio to rpm2archive, but it can't rebuild RPM because it handles outcome of rpm2archive wrongly. It will be fixed in rpmrebuild 2.21.
See
rpmrebuild 2.20: rpm2archive called with incorrect arguments
https://sourceforge.net/p/rpmrebuild/bugs/18/
=> ci: extract setup rpmrebuild and fix rebuild

.github/workflows/maintenance-bundle-update.yml
When kicked from LTS branch, base branch should be set explicitly, otherwise PR will be created against main branch.
=> ci: refer base branch name

.github/workflows/maintenance-bundle-update.yml
Try to use $Env:GITHUB_REF_NAME which contains branch name
github.base_ref is empty when executing via workflow_dispatch.
=> ci: fix empty base_ref error

fluent-package/make-index-html.erb
On object storage, directory index is not available, so use generated DIRECTORY/index.html explicitly.
=> package: navigate with index.html explicitly

.github/workflows/yum.yml
AmazonLinux 2023 contains code for CGroup v1, but it is not officially supported.
See https://docs.aws.amazon.com/eks/latest/userguide/al2023.html
While AL2023 still includes code that can make the system run using
cgroupv1, this isn’t a recommended or supported configuration. This
configuration will be completely removed in a future major release of
Amazon Linux.
=> ci: fix wrong grouping about CGroup v1

.github/workflows/yum-arm.matrix.json, .github/workflows/yum.matrix.json, fluent-package/Rakefile, fluent-package/test-verify-repo.sh
AL2 will not be supported for upcoming v6.
Keep the recipe as same as CentOS for a while.
=> rpm: drop AmazonLinux 2 from default target

.github/workflows/yum-arm.matrix.json, .github/workflows/yum.matrix.json, fluent-package/Gemfile, fluent-package/Gemfile.lock, fluent-package/Rakefile, fluent-package/yum/almalinux-10-aarch64/from, fluent-package/yum/almalinux-10/Dockerfile, fluent-package/yum/almalinux-10/qemu-dummy-static, lib/yum/build.sh
NOTE: RHEL10 reached general availability (GA)
=> rpm: add almalinux:10

fluent-package/msi/source.wxs
See
https://docs.firegiant.com/wix3/wixui/wixui_customizations/
https://docs.firegiant.com/wix3/tutorial/net-and-net/launch-the-internet/
=> msi: show checkbox to guide release note

fluent-package/debian/lintian/fluent-package/ubuntu.profile
It fixes the following error:
```
Please use spaces as separators in field Disable-Tags instead of commas in profile /root/.lintian/profiles/fluent-package/ubuntu.profile
Error: The operation was canceled.
```
=> deb: use appropriate separator for lintian

.github/workflows/bundle-audit.yml, .github/workflows/windows.yml, fluent-package/msi/Dockerfile
See Windows Server 2019 is closing down
https://github.blog/changelog/2025-04-15-upcoming-breaking-changes-and-releases-for-github-actions/
We’re beginning the process of closing down the Windows server 2019
hosted runner image, following our N-1 OS support policy. This image
will be fully retired by June 30, 2025.
---------
=> Backport: windows: bump version to Windows Server 2022 (#849)

.github/workflows/yum.yml
* Backport #844
In current situation, there is no better solution
to keep systemd test cases on AmazonLinux:2 sustainable.
(In other words, keeping AL2 priority is not so high)
Before:
* Build package for AL2 and test with container and systemd CI
After:
* Build package for AL2 and test with container
=> Backport: ci: disable AmazonLinux:2 systemd test cases (#844)

fluent-package/yum/fluent-package.spec.in
When install fluent-package on rhel8 and other,
it will install unnecessary ruby packages as dependencies.
```
Last metadata expiration check: 0:00:02 ago on Thu Jul 31 03:28:14 2025.                                                                    
Dependencies resolved.                                                                                                                      
===============================================================================================                                             
Package                Arch    Version                                   Repository       Size                                             
=============================================================================================== …
```
=> Exclude dependency for ruby packages

fluent-apt-source/Rakefile, fluent-apt-source/debian/changelog, fluent-apt-source/debian/rules, fluent-lts-apt-source/Rakefile, fluent-lts-apt-source/debian/changelog, fluent-lts-apt-source/debian/rules
Since v6, we switch from packages.treasuredata.com to fluentd.cdn.cncf.io.
For a while, packages will be uploaded into both of them.
=> Use fluentd.cdn.cncf.io

fluent-package/yum/fluent-package.spec.in
The user can refer the Ruby configure results through `RbConfig::CONFIG`.
`RbConfig::CONFIG` is mainly used when installing gems which has C extension.
If flags remain that use linker scripts that do not exist in the user's environment,
it causes errors when user install the gem.
When creating a package using `fluent-package.spec.in`, the environment variable `LDFLAGS` was automatically set as follows.
```
LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1    -Wl,--build-id=sha1 -Wl,-dT,/root/rpmbuild/BUILD/fluent-package-6.0.0/.package_note-fluent-package-6.0.0-1.amzn2023.x86_64.ld'
```
Ruby's `configure` refers to the environment variable `LDFLAGS`,
and it expands into `RbConfig::CONFIG`.
Fix …
=> yum: Disable package-note-file to remove unnecessary linker flag

.github/workflows/maintenance-bundle-update.yml
I forgot to update Ruby version in `maintenance-bundle-update.yml`
It should have same Ruby version in 
https://github.com/fluent/fluent-package-builder/blob/401960014daeb15ede44fcdc76ee373d65ffce34/fluent-package/config.rb#L26
=> ci: update Ruby version in maintenance workflow

.github/workflows/maintenance-bundle-update.yml
Reverts fluent/fluent-package-builder#880
Unfortunately, this workflow still causes build error when compile libiconv.
```
2025-08-23T04:57:37.3576074Z -Wno-error=sign-conversion -O2 -g -fPIC
2025-08-23T04:57:37.3576954Z -DLIBDIR=\"C:/hostedtoolcache/windows/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/nokogiri-1.18.9/ports/x64-mingw-ucrt/libiconv/1.17/lib\"
2025-08-23T04:57:37.3577964Z -DBUILDING_LIBICONV -DBUILDING_LIBCHARSET -DBUILDING_DLL -DENABLE_RELOCATABLE=1
2025-08-23T04:57:37.3578483Z -DIN_LIBRARY
2025-08-23T04:57:37.3579197Z -DINSTALLDIR=\"C:/hostedtoolcache/windows/Ruby/3.4.5/x64/lib/ruby/gems/3.4.0/gems/nokogiri-1.18.9/ports/x64-mingw-ucrt/libiconv/1.17/lib\"
2025-08-23T04:57:37.3580176Z -DNO_XMALLOC -Dset_relocation_prefix=libiconv_set_relocation_prefix …
```
=> Revert "ci: add compiler flag to avoid build error"

fluent-package/Gemfile, fluent-package/Gemfile.lock
Related to https://github.com/uken/fluent-plugin-elasticsearch/issues/1061#issuecomment-2912230835
elasticsearch 9 series does not support ES8.
We should consider ES8 as the default version for a while.
Users who want to use ES9 need to update the gems manually.
=> Use elasticsearch 8 series

fluent-package/convert-artifacts-layout.sh
Recently fluent-release package was introduced, to convey them correctly from artifacts to our 
repository layout, need to support it explicitly.
=> rpm: support to convert fluent-release package too

fluent-package/yum/systemd-test/update-to-next-major-version.sh
The new test code are from other update-to-next-version tests.
Those tests need rpmrebuild, but looks like it is not supported on EPEL for AlmaLinux 10 yet.
So, those tests can not be done for AlmaLinux 10.
It would be better to cover those tests on this test as well.
=> ci: reinforce update-to-next-major-version test

fluent-apt-source/debian/rules, fluent-lts-apt-source/debian/rules
It is better to specify supported architectures in Architectures: field explicitly.
Without it, if other architecture was enabled (e.g. i386 was enabled additionally with multiarch), apt emits the following message:
```
Notice: Skipping acquire of configured file
'contrib/binary-i386/Packages' as repository
'https://fluentd.cdn.cncf.io/lts/6/debian/trixie trixie InRelease'
doesn't support architecture 'i386'
```
=> deb: add missing Architectures: field

fluent-package/update-gemfile.rb
For LTS channel:
$ ruby update-gemfile.rb --lts
For standard channel:
$ ruby update-gemfile.rb
=> packages: add helper script to update gemfile

fluent-lts-release/yum/fluent-lts-release.spec.in, fluent-release/yum/fluent-release.spec.in
Currently, the following dependencies are installed. (Confirmed on AlmaLinux 8)
* dbus-glib
* dnf-plugins-core
* epel-release
* python3-dateutil
* python3-dbus
* python3-dnf-plugins
* python3-six
* python3-systemd
These dependencies would not be intended.
Especially, it appears that `epel-release` could not be installed on RHEL.
=> fluent-release: remove unnecessary dependencies

.github/workflows/yum.yml
This PR will fix backport error in #917
When I solve the conflict, I introduced the error.
Therefore, the `yum` workflow does not works properly.
=> v5: ci: fix backport error

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/tmpfiles.sh, fluent-package/templates/usr/lib/tmpfiles.d/fluentd.conf, fluent-package/yum/systemd-test/tmpfiles.sh
We should exclude `/tmp/fluentd-lock-*` directory.
If `/tmp/fluentd-lock-*` is cleaned up while Fluentd is running:
* out_file can fail flushing.
* out_secondary can fail flushing.
* The supervisor process exit abnormally when Fluentd stops.
At least, RHEL 8 has the following default conf for tmpfiles.d:
/usr/lib/tmpfiles.d/tmp.conf
q /tmp 1777 root root 10d
This can delete directories under `/tmp` if they are not used for more than 10 days.
We don't need to protect the old lock files under
`/tmp/fluentd-lock-*/`, so use `X` instead of `x`.
In configs where lock files are not used, there is no problem even if this directory is deleted.
In configurations that do use lock files, it’s unlikely that this directory would not be updated for more than 10 days. Therefore, the cases where this …
=> tmpfiles.d: ensure tmp dir for lock files not be cleaned up

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/tmpfiles.sh, fluent-package/templates/usr/lib/tmpfiles.d/fluentd.conf, fluent-package/yum/systemd-test/tmpfiles.sh
Backport #921
We should exclude `/tmp/fluentd-lock-*` directory. If `/tmp/fluentd-lock-*` is cleaned up while Fluentd is running:
* out_file can fail flushing.
* out_secondary can fail flushing.
* The supervisor process exit abnormally when Fluentd stops.
At least, RHEL 8 has the following default conf for tmpfiles.d:
/usr/lib/tmpfiles.d/tmp.conf
q /tmp 1777 root root 10d
This can delete directories under `/tmp` if they are not used for more than 10 days.
We don't need to protect the old lock files under
`/tmp/fluentd-lock-*/`, so use `X` instead of `x`.
In configs where lock files are not used, there is no problem even if this directory is deleted.
In configurations that do use lock files, it’s unlikely that this directory would not be updated for more than 10 days. Therefore, the cases …
=> Backport(v6): tmpfiles.d: ensure tmp dir for lock files not be cleaned up (#921)

.github/workflows/apt.yml, .github/workflows/yum.yml, fluent-package/apt/systemd-test/tmpfiles.sh, fluent-package/templates/usr/lib/tmpfiles.d/fluentd.conf, fluent-package/yum/systemd-test/tmpfiles.sh
Backport #921
We should exclude `/tmp/fluentd-lock-*` directory. If `/tmp/fluentd-lock-*` is cleaned up while Fluentd is running:
* out_file can fail flushing.
* out_secondary can fail flushing.
* The supervisor process exit abnormally when Fluentd stops.
At least, RHEL 8 has the following default conf for tmpfiles.d:
/usr/lib/tmpfiles.d/tmp.conf
q /tmp 1777 root root 10d
This can delete directories under `/tmp` if they are not used for more than 10 days.
We don't need to protect the old lock files under
`/tmp/fluentd-lock-*/`, so use `X` instead of `x`.
In configs where lock files are not used, there is no problem even if this directory is deleted.
In configurations that do use lock files, it’s unlikely that this directory would not be updated for more than 10 days. Therefore, the cases …
=> Backport(v5): tmpfiles.d: ensure tmp dir for lock files not be cleaned up (#921)
